#include "compiler/builtin_catalog_internal.hpp"

namespace strata::compiler {

void add_builtin_collection_widgets(BuiltinCatalog& catalog) {
    const DeclaredParameter on_scroll{
        .name = "onScroll",
        .type = declared_type_reference("t36"),
    };
    const DeclaredWidgetEvent effective_scroll_event{
        .name = "scroll",
        .callback_parameter = "onScroll",
        .description =
            "Emitted once for each effective clamped scroll-offset change from wheel, drag, "
            "animation, focus reveal, or programmatic scroll.",
        .phase = "post-mutation",
    };
    catalog.widgets.insert(
        catalog.widgets.end(),
        {
            DeclaredWidget{
                .name = "ItemGrid",
                .parameters =
                    {DeclaredParameter{.name = "entries",
                                       .type = declared_type_reference("t113"),
                                       .required = true},
                     DeclaredParameter{.name = "selectionMode",
                                       .type = declared_type_reference("t115")},
                     DeclaredParameter{.name = "selectedKeys",
                                       .type = declared_type_reference("t116"),
                                       .nullable = true},
                     DeclaredParameter{.name = "defaultSelectedKeys",
                                       .type = declared_type_reference("t116")},
                     DeclaredParameter{.name = "columns", .type = declared_type_reference("t3")},
                     DeclaredParameter{.name = "cellWidth", .type = declared_type_reference("t3")},
                     DeclaredParameter{.name = "cellHeight", .type = declared_type_reference("t3")},
                     DeclaredParameter{.name = "gap", .type = declared_type_reference("t3")},
                     DeclaredParameter{.name = "overscan", .type = declared_type_reference("t3")},
                     DeclaredParameter{.name = "itemTemplate",
                                       .type = declared_type_reference("t117")},
                     DeclaredParameter{.name = "onSelect", .type = declared_type_reference("t36")},
                     DeclaredParameter{.name = "onActivate",
                                       .type = declared_type_reference("t36")},
                     DeclaredParameter{.name = "onContext", .type = declared_type_reference("t36")},
                     on_scroll,
                     DeclaredParameter{.name = "bind", .type = declared_type_reference("t7")}},
                .parameter_order = {"entries",
                                    "key",
                                    "selectionMode",
                                    "selectedKeys",
                                    "defaultSelectedKeys",
                                    "columns",
                                    "cellWidth",
                                    "cellHeight",
                                    "gap",
                                    "overscan",
                                    "itemTemplate",
                                    "layout",
                                    "variant",
                                    "style",
                                    "visualStyle",
                                    "effect",
                                    "material",
                                    "transition",
                                    "enter",
                                    "exit",
                                    "move",
                                    "motions",
                                    "animateChanges",
                                    "animateContentSize",
                                    "disclosure",
                                    "contentKey",
                                    "contentTransition",
                                    "contentTransitionMode",
                                    "stagger",
                                    "semantics",
                                    "onSelect",
                                    "onActivate",
                                    "onContext",
                                    "onScroll",
                                    "bind",
                                    "textStyle",
                                    "textVisualStyle",
                                    "animation",
                                    "behaviors"},
                .bindings = {DeclaredWidgetBinding{.shorthand_parameter = "bind",
                                                   .value_parameter = "selectedKeys",
                                                   .event_parameter = "onSelect"}},
                .events = {DeclaredWidgetEvent{.name = "selection change",
                                               .callback_parameter = "onSelect",
                                               .description =
                                                   "Carries the complete stable-key selection from "
                                                   "click, keyboard, or marquee."},
                           DeclaredWidgetEvent{.name = "item activation",
                                               .callback_parameter = "onActivate",
                                               .description = "Carries the activated item key."},
                           DeclaredWidgetEvent{
                               .name = "context request",
                               .callback_parameter = "onContext",
                               .description =
                                   "Carries the item key and pointer position when available."},
                           effective_scroll_event},
                .capabilities = {"effective-scroll"},
                .retained_state =
                    {DeclaredRetainedState{.name = "selection",
                                           .description =
                                               "Uncontrolled selection, range anchor, active cell, "
                                               "typeahead, and marquee geometry."},
                     DeclaredRetainedState{
                         .name = "scrollOffset",
                         .description =
                             "Virtual row-band viewport offset and sticky group position."}}},
            DeclaredWidget{
                .name = "Repeater",
                .parameters =
                    {DeclaredParameter{.name = "estimatedItemExtent",
                                       .type = declared_type_reference("t3")},
                     DeclaredParameter{.name = "axis", .type = declared_type_reference("t28")},
                     DeclaredParameter{.name = "overscan", .type = declared_type_reference("t3")},
                     DeclaredParameter{.name = "viewportInsets",
                                       .type = declared_type_reference("t61")},
                     DeclaredParameter{.name = "contentPadding",
                                       .type = declared_type_reference("t61")},
                     DeclaredParameter{.name = "scrollbarGutter",
                                       .type = declared_type_reference("t3")},
                     on_scroll},
                .parameter_order = {"estimatedItemExtent",
                                    "key",
                                    "axis",
                                    "overscan",
                                    "viewportInsets",
                                    "contentPadding",
                                    "scrollbarGutter",
                                    "onScroll",
                                    "layout",
                                    "variant",
                                    "style",
                                    "visualStyle",
                                    "effect",
                                    "material",
                                    "transition",
                                    "enter",
                                    "exit",
                                    "move",
                                    "motions",
                                    "animateChanges",
                                    "animateContentSize",
                                    "disclosure",
                                    "contentKey",
                                    "contentTransition",
                                    "contentTransitionMode",
                                    "stagger",
                                    "semantics",
                                    "textStyle",
                                    "textVisualStyle",
                                    "animation",
                                    "behaviors"},
                .bindings = {},
                .events = {effective_scroll_event},
                .capabilities = {"effective-scroll"},
                .retained_state =
                    {DeclaredRetainedState{
                         .name = "scrollOffset",
                         .description = "Key-anchored scroll offset for the retained viewport."},
                     DeclaredRetainedState{.name = "measurements",
                                           .description =
                                               "Measured row extents cached by stable item key."}},
                .allows_children = true},
            DeclaredWidget{
                .name = "Scroll",
                .parameters =
                    {DeclaredParameter{.name = "horizontal", .type = declared_type_reference("t2")},
                     DeclaredParameter{.name = "vertical", .type = declared_type_reference("t2")},
                     DeclaredParameter{.name = "clip", .type = declared_type_reference("t2")},
                     DeclaredParameter{.name = "viewportInsets",
                                       .type = declared_type_reference("t61")},
                     DeclaredParameter{.name = "contentPadding",
                                       .type = declared_type_reference("t61")},
                     DeclaredParameter{.name = "scrollbarGutter",
                                       .type = declared_type_reference("t3")},
                     on_scroll},
                .parameter_order = {"key",
                                    "horizontal",
                                    "vertical",
                                    "clip",
                                    "viewportInsets",
                                    "contentPadding",
                                    "scrollbarGutter",
                                    "onScroll",
                                    "layout",
                                    "variant",
                                    "style",
                                    "visualStyle",
                                    "effect",
                                    "material",
                                    "transition",
                                    "enter",
                                    "exit",
                                    "move",
                                    "motions",
                                    "animateChanges",
                                    "animateContentSize",
                                    "disclosure",
                                    "contentKey",
                                    "contentTransition",
                                    "contentTransitionMode",
                                    "stagger",
                                    "semantics",
                                    "textStyle",
                                    "textVisualStyle",
                                    "animation",
                                    "behaviors"},
                .bindings = {},
                .events = {effective_scroll_event},
                .capabilities = {"effective-scroll"},
                .retained_state = {DeclaredRetainedState{
                    .name = "scrollOffset", .description = "Current clamped viewport offset."}},
                .allows_children = true},
            DeclaredWidget{
                .name = "Table",
                .parameters =
                    {DeclaredParameter{.name = "columns",
                                       .type = declared_type_reference("t118"),
                                       .required = true},
                     DeclaredParameter{
                         .name = "rows",
                         .type = declared_type(DeclaredType{
                             .kind = DeclaredTypeKind::union_value,
                             .label = "table rows or async table rows",
                             .options = {declared_type_reference("t121"),
                                         declared_type(DeclaredType{
                                             .kind = DeclaredTypeKind::async_value,
                                             .value = declared_type_reference("t121")})}}),
                         .required = true},
                     DeclaredParameter{.name = "selectionMode",
                                       .type = declared_type_reference("t115")},
                     DeclaredParameter{.name = "selectedKeys",
                                       .type = declared_type_reference("t116"),
                                       .nullable = true},
                     DeclaredParameter{.name = "defaultSelectedKeys",
                                       .type = declared_type_reference("t116")},
                     DeclaredParameter{.name = "columnWidths",
                                       .type = declared_type_reference("t124"),
                                       .nullable = true},
                     DeclaredParameter{.name = "defaultColumnWidths",
                                       .type = declared_type_reference("t124")},
                     DeclaredParameter{.name = "columnOrder",
                                       .type = declared_type_reference("t78"),
                                       .nullable = true},
                     DeclaredParameter{.name = "defaultColumnOrder",
                                       .type = declared_type_reference("t78")},
                     DeclaredParameter{.name = "sortColumn",
                                       .type = declared_type_reference("t0"),
                                       .nullable = true},
                     DeclaredParameter{.name = "sortDirection",
                                       .type = declared_type_reference("t126"),
                                       .nullable = true},
                     DeclaredParameter{.name = "rowHeight", .type = declared_type_reference("t3")},
                     DeclaredParameter{.name = "headerHeight",
                                       .type = declared_type_reference("t3")},
                     DeclaredParameter{.name = "overscan", .type = declared_type_reference("t3")},
                     DeclaredParameter{.name = "focusMode",
                                       .type = declared_type_reference("t127")},
                     DeclaredParameter{.name = "presentation",
                                       .type = declared_type_reference("t128")},
                     DeclaredParameter{.name = "rowTemplate",
                                       .type = declared_type_reference("t129")},
                     DeclaredParameter{.name = "cellTemplate",
                                       .type = declared_type_reference("t130")},
                     DeclaredParameter{.name = "cellTemplates",
                                       .type = declared_type_reference("t131")},
                     DeclaredParameter{.name = "emptyContent",
                                       .type = declared_type_reference("t133")},
                     DeclaredParameter{.name = "loadingContent",
                                       .type = declared_type_reference("t133")},
                     DeclaredParameter{.name = "noMatchesContent",
                                       .type = declared_type_reference("t133")},
                     DeclaredParameter{.name = "onSelect", .type = declared_type_reference("t36")},
                     DeclaredParameter{.name = "onActivate",
                                       .type = declared_type_reference("t36")},
                     DeclaredParameter{.name = "onContext", .type = declared_type_reference("t36")},
                     DeclaredParameter{.name = "onSort", .type = declared_type_reference("t36")},
                     DeclaredParameter{.name = "onColumnResize",
                                       .type = declared_type_reference("t36")},
                     DeclaredParameter{.name = "onColumnReorder",
                                       .type = declared_type_reference("t36")},
                     DeclaredParameter{.name = "bind", .type = declared_type_reference("t7")},
                     on_scroll,
                     DeclaredParameter{.name = "loadingText",
                                       .type = declared_type_reference("t0")},
                     DeclaredParameter{.name = "errorText", .type = declared_type_reference("t0")},
                     DeclaredParameter{.name = "emptyText", .type = declared_type_reference("t0")}},
                .parameter_order = {"columns",
                                    "rows",
                                    "key",
                                    "selectionMode",
                                    "selectedKeys",
                                    "defaultSelectedKeys",
                                    "columnWidths",
                                    "defaultColumnWidths",
                                    "columnOrder",
                                    "defaultColumnOrder",
                                    "sortColumn",
                                    "sortDirection",
                                    "rowHeight",
                                    "headerHeight",
                                    "overscan",
                                    "focusMode",
                                    "presentation",
                                    "rowTemplate",
                                    "cellTemplate",
                                    "cellTemplates",
                                    "emptyContent",
                                    "loadingContent",
                                    "noMatchesContent",
                                    "layout",
                                    "variant",
                                    "style",
                                    "visualStyle",
                                    "effect",
                                    "material",
                                    "transition",
                                    "enter",
                                    "exit",
                                    "move",
                                    "motions",
                                    "animateChanges",
                                    "animateContentSize",
                                    "disclosure",
                                    "contentKey",
                                    "contentTransition",
                                    "contentTransitionMode",
                                    "stagger",
                                    "semantics",
                                    "onSelect",
                                    "onActivate",
                                    "onContext",
                                    "onSort",
                                    "onColumnResize",
                                    "onColumnReorder",
                                    "onScroll",
                                    "bind",
                                    "textStyle",
                                    "textVisualStyle",
                                    "animation",
                                    "behaviors",
                                    "loadingText",
                                    "errorText",
                                    "emptyText"},
                .bindings = {DeclaredWidgetBinding{.shorthand_parameter = "bind",
                                                   .value_parameter = "selectedKeys",
                                                   .event_parameter = "onSelect"}},
                .events =
                    {DeclaredWidgetEvent{.name = "selection change",
                                         .callback_parameter = "onSelect",
                                         .description =
                                             "Carries the complete stable-key row selection."},
                     DeclaredWidgetEvent{.name = "row activation",
                                         .callback_parameter = "onActivate",
                                         .description = "Carries the activated row key."},
                     DeclaredWidgetEvent{
                         .name = "row context request",
                         .callback_parameter = "onContext",
                         .description = "Carries the row key and pointer position when available."},
                     DeclaredWidgetEvent{.name = "sort request",
                                         .callback_parameter = "onSort",
                                         .description =
                                             "Carries a controlled column id and direction cycle; "
                                             "rows remain host ordered."},
                     DeclaredWidgetEvent{.name = "column width change",
                                         .callback_parameter = "onColumnResize",
                                         .description = "Carries a column id and requested width."},
                     DeclaredWidgetEvent{.name = "column reorder",
                                         .callback_parameter = "onColumnReorder",
                                         .description =
                                             "Carries a column id and target display index."},
                     effective_scroll_event},
                .capabilities = {"effective-scroll"},
                .retained_state =
                    {DeclaredRetainedState{.name = "selection",
                                           .description = "Uncontrolled row selection, anchor, "
                                                          "active row, and typeahead buffer."},
                     DeclaredRetainedState{.name = "columnWidths",
                                           .description =
                                               "Uncontrolled widths keyed by column id."},
                     DeclaredRetainedState{.name = "contentWidths",
                                           .description =
                                               "Measured minima for content-sized columns, grown "
                                               "from materialized cells."},
                     DeclaredRetainedState{.name = "columnOrder",
                                           .description = "Uncontrolled visible column order."},
                     DeclaredRetainedState{
                         .name = "scrollOffset",
                         .description = "Vertical row window and horizontal wide-table offset."}}},
            DeclaredWidget{
                .name = "TreeView",
                .parameters =
                    {DeclaredParameter{
                         .name = "items",
                         .type = declared_type(DeclaredType{
                             .kind = DeclaredTypeKind::union_value,
                             .label = "tree items or async tree items",
                             .options = {declared_type_reference("t136"),
                                         declared_type(DeclaredType{
                                             .kind = DeclaredTypeKind::async_value,
                                             .value = declared_type_reference("t136")})}}),
                         .required = true},
                     DeclaredParameter{.name = "selectionMode",
                                       .type = declared_type_reference("t115")},
                     DeclaredParameter{.name = "selectedKeys",
                                       .type = declared_type_reference("t116"),
                                       .nullable = true},
                     DeclaredParameter{.name = "defaultSelectedKeys",
                                       .type = declared_type_reference("t116")},
                     DeclaredParameter{.name = "expandedKeys",
                                       .type = declared_type_reference("t116"),
                                       .nullable = true},
                     DeclaredParameter{.name = "defaultExpandedKeys",
                                       .type = declared_type_reference("t116")},
                     DeclaredParameter{.name = "rowHeight", .type = declared_type_reference("t3")},
                     DeclaredParameter{.name = "indent", .type = declared_type_reference("t3")},
                     DeclaredParameter{.name = "disclosureSize",
                                       .type = declared_type_reference("t3")},
                     DeclaredParameter{.name = "showIndentGuides",
                                       .type = declared_type_reference("t2")},
                     DeclaredParameter{.name = "hoverExpandDelay",
                                       .type = declared_type_reference("t9")},
                     DeclaredParameter{.name = "overscan", .type = declared_type_reference("t3")},
                     DeclaredParameter{.name = "rowTemplate",
                                       .type = declared_type_reference("t138")},
                     DeclaredParameter{.name = "onSelect", .type = declared_type_reference("t36")},
                     DeclaredParameter{.name = "onActivate",
                                       .type = declared_type_reference("t36")},
                     DeclaredParameter{.name = "onContext", .type = declared_type_reference("t36")},
                     DeclaredParameter{.name = "onExpand", .type = declared_type_reference("t36")},
                     DeclaredParameter{.name = "onLoadChildren",
                                       .type = declared_type_reference("t36")},
                     DeclaredParameter{.name = "onDrop", .type = declared_type_reference("t36")},
                     on_scroll,
                     DeclaredParameter{.name = "bind", .type = declared_type_reference("t7")},
                     DeclaredParameter{.name = "loadingText",
                                       .type = declared_type_reference("t0")},
                     DeclaredParameter{.name = "errorText", .type = declared_type_reference("t0")},
                     DeclaredParameter{.name = "emptyText", .type = declared_type_reference("t0")}},
                .parameter_order =
                    {"items",
                     "key",
                     "selectionMode",
                     "selectedKeys",
                     "defaultSelectedKeys",
                     "expandedKeys",
                     "defaultExpandedKeys",
                     "rowHeight",
                     "indent",
                     "disclosureSize",
                     "showIndentGuides",
                     "hoverExpandDelay",
                     "overscan",
                     "rowTemplate",
                     "layout",
                     "variant",
                     "style",
                     "visualStyle",
                     "effect",
                     "material",
                     "transition",
                     "enter",
                     "exit",
                     "move",
                     "motions",
                     "animateChanges",
                     "animateContentSize",
                     "disclosure",
                     "contentKey",
                     "contentTransition",
                     "contentTransitionMode",
                     "stagger",
                     "semantics",
                     "onSelect",
                     "onActivate",
                     "onContext",
                     "onExpand",
                     "onLoadChildren",
                     "onDrop",
                     "onScroll",
                     "bind",
                     "textStyle",
                     "textVisualStyle",
                     "animation",
                     "behaviors",
                     "loadingText",
                     "errorText",
                     "emptyText"},
                .bindings = {DeclaredWidgetBinding{.shorthand_parameter = "bind",
                                                   .value_parameter = "selectedKeys",
                                                   .event_parameter = "onSelect"}},
                .events =
                    {DeclaredWidgetEvent{
                         .name = "selection change",
                         .callback_parameter = "onSelect",
                         .description =
                             "Carries the complete stable-key selection, anchor, and active key."},
                     DeclaredWidgetEvent{.name = "item activation",
                                         .callback_parameter = "onActivate",
                                         .description = "Carries the activated stable item key."},
                     DeclaredWidgetEvent{
                         .name = "context request",
                         .callback_parameter = "onContext",
                         .description =
                             "Carries the item key and pointer position when available."},
                     DeclaredWidgetEvent{.name = "expansion change",
                                         .callback_parameter = "onExpand",
                                         .description = "Carries the requested expansion state and "
                                                        "complete expanded-key set."},
                     DeclaredWidgetEvent{.name = "lazy children request",
                                         .callback_parameter = "onLoadChildren",
                                         .description =
                                             "Carries the first expanded lazy node key."},
                     DeclaredWidgetEvent{
                         .name = "tree drop",
                         .callback_parameter = "onDrop",
                         .description =
                             "Carries dragged keys, target key, and before/on/after position."},
                     effective_scroll_event},
                .capabilities = {"effective-scroll"},
                .retained_state =
                    {DeclaredRetainedState{.name = "selection",
                                           .description =
                                               "Uncontrolled selected keys, range anchor, active "
                                               "key, and typeahead buffer."},
                     DeclaredRetainedState{
                         .name = "expansion",
                         .description =
                             "Uncontrolled expanded keys and pending lazy-child requests."},
                     DeclaredRetainedState{.name = "scrollOffset",
                                           .description = "Virtual tree viewport offset."}}},
            DeclaredWidget{
                .name = "VirtualList",
                .parameters =
                    {DeclaredParameter{.name = "itemCount", .type = declared_type_reference("t3")},
                     DeclaredParameter{.name = "itemExtent",
                                       .type = declared_type_reference("t3"),
                                       .required = true},
                     DeclaredParameter{.name = "items", .type = declared_type_reference("t158")},
                     DeclaredParameter{.name = "itemTemplate",
                                       .type = declared_type_reference("t159")},
                     DeclaredParameter{.name = "loadingText",
                                       .type = declared_type_reference("t0")},
                     DeclaredParameter{.name = "errorText", .type = declared_type_reference("t0")},
                     DeclaredParameter{.name = "emptyText", .type = declared_type_reference("t0")},
                     DeclaredParameter{.name = "axis", .type = declared_type_reference("t28")},
                     DeclaredParameter{.name = "overscan", .type = declared_type_reference("t3")},
                     DeclaredParameter{.name = "viewportInsets",
                                       .type = declared_type_reference("t61")},
                     DeclaredParameter{.name = "contentPadding",
                                       .type = declared_type_reference("t61")},
                     DeclaredParameter{.name = "scrollbarGutter",
                                       .type = declared_type_reference("t3")},
                     on_scroll},
                .parameter_order = {"itemCount",
                                    "itemExtent",
                                    "items",
                                    "itemTemplate",
                                    "loadingText",
                                    "errorText",
                                    "emptyText",
                                    "key",
                                    "axis",
                                    "overscan",
                                    "viewportInsets",
                                    "contentPadding",
                                    "scrollbarGutter",
                                    "onScroll",
                                    "layout",
                                    "variant",
                                    "style",
                                    "visualStyle",
                                    "effect",
                                    "material",
                                    "transition",
                                    "enter",
                                    "exit",
                                    "move",
                                    "motions",
                                    "animateChanges",
                                    "animateContentSize",
                                    "disclosure",
                                    "contentKey",
                                    "contentTransition",
                                    "contentTransitionMode",
                                    "stagger",
                                    "semantics",
                                    "textStyle",
                                    "textVisualStyle",
                                    "animation",
                                    "behaviors"},
                .bindings = {},
                .events = {effective_scroll_event},
                .capabilities = {"effective-scroll"},
                .retained_state = {DeclaredRetainedState{
                    .name = "scrollOffset",
                    .description =
                        "Horizontal or vertical scroll offset for the retained viewport."}},
                .allows_children = true},
        });
}

} // namespace strata::compiler
