#include "compiler/builtin_catalog_internal.hpp"

namespace strata::compiler {

void add_builtin_actions(BuiltinCatalog& catalog) {
    catalog.actions = {
        DeclaredAction{.id = "Button",
                       .parameters = {},
                       .dispatch_policy = "optional",
                       .payload_contract = "no payload",
                       .summary = "Observe the built-in Button interaction"},
        DeclaredAction{.id = "Checkbox",
                       .parameters = {},
                       .dispatch_policy = "optional",
                       .payload_contract = "no payload",
                       .summary = "Observe the built-in Checkbox interaction"},
        DeclaredAction{.id = "ComboBoxQuery",
                       .parameters = {},
                       .dispatch_policy = "optional",
                       .payload_contract = "no payload",
                       .summary = "Observe the built-in ComboBoxQuery interaction"},
        DeclaredAction{.id = "ComboBoxSelect",
                       .parameters = {},
                       .dispatch_policy = "optional",
                       .payload_contract = "no payload",
                       .summary = "Observe the built-in ComboBoxSelect interaction"},
        DeclaredAction{.id = "ContextMenu",
                       .parameters = {},
                       .dispatch_policy = "optional",
                       .payload_contract = "no payload",
                       .summary = "Observe the built-in ContextMenu interaction"},
        DeclaredAction{.id = "IconButton",
                       .parameters = {},
                       .dispatch_policy = "optional",
                       .payload_contract = "no payload",
                       .summary = "Observe the built-in IconButton interaction"},
        DeclaredAction{.id = "List",
                       .parameters = {},
                       .dispatch_policy = "optional",
                       .payload_contract = "no payload",
                       .summary = "Observe the built-in List interaction"},
        DeclaredAction{.id = "Menu",
                       .parameters = {},
                       .dispatch_policy = "optional",
                       .payload_contract = "no payload",
                       .summary = "Observe the built-in Menu interaction"},
        DeclaredAction{.id = "NumberField",
                       .parameters = {},
                       .dispatch_policy = "optional",
                       .payload_contract = "no payload",
                       .summary = "Observe the built-in NumberField interaction"},
        DeclaredAction{.id = "RadioGroup",
                       .parameters = {},
                       .dispatch_policy = "optional",
                       .payload_contract = "no payload",
                       .summary = "Observe the built-in RadioGroup interaction"},
        DeclaredAction{.id = "Select",
                       .parameters = {},
                       .dispatch_policy = "optional",
                       .payload_contract = "no payload",
                       .summary = "Observe the built-in Select interaction"},
        DeclaredAction{.id = "Slider",
                       .parameters = {},
                       .dispatch_policy = "optional",
                       .payload_contract = "no payload",
                       .summary = "Observe the built-in Slider interaction"},
        DeclaredAction{.id = "Tabs",
                       .parameters = {},
                       .dispatch_policy = "optional",
                       .payload_contract = "no payload",
                       .summary = "Observe the built-in Tabs interaction"},
        DeclaredAction{.id = "Toggle",
                       .parameters = {},
                       .dispatch_policy = "optional",
                       .payload_contract = "no payload",
                       .summary = "Observe the built-in Toggle interaction"},
        DeclaredAction{.id = "action.parallel",
                       .parameters = {},
                       .dispatch_policy = "framework",
                       .payload_contract = "strata.action-payload/action.parallel@1",
                       .summary = "Execute independent UI-local actions as one activation"},
        DeclaredAction{.id = "action.sequence",
                       .parameters = {},
                       .dispatch_policy = "framework",
                       .payload_contract = "strata.action-payload/action.sequence@1",
                       .summary = "Execute UI-local actions in order"},
        DeclaredAction{.id = "application.redo",
                       .parameters = {},
                       .dispatch_policy = "framework",
                       .payload_contract = "no payload",
                       .summary = "Redo the latest application state mutation"},
        DeclaredAction{.id = "application.undo",
                       .parameters = {},
                       .dispatch_policy = "framework",
                       .payload_contract = "no payload",
                       .summary = "Undo the latest application state mutation"},
        DeclaredAction{.id = "async.cancel",
                       .parameters = {DeclaredParameter{.name = "requestId",
                                                        .type = declared_type_reference("t3"),
                                                        .required = true}},
                       .dispatch_policy = "framework",
                       .payload_contract = "strata.action-payload/async.cancel@1",
                       .summary = "Cancel an asynchronous host query"},
        DeclaredAction{
            .id = "async.query",
            .parameters =
                {DeclaredParameter{
                     .name = "binding", .type = declared_type_reference("t0"), .required = true},
                 DeclaredParameter{
                     .name = "payload", .type = declared_type_reference("t7"), .nullable = true},
                 DeclaredParameter{.name = "debounceMillis", .type = declared_type_reference("t3")},
                 DeclaredParameter{.name = "fromEvent", .type = declared_type_reference("t2")}},
            .dispatch_policy = "framework",
            .payload_contract = "strata.action-payload/async.query@1",
            .summary = "Start a debounced latest-wins asynchronous host query"},
        DeclaredAction{.id = "command.execute",
                       .parameters = {DeclaredParameter{
                           .name = "id", .type = declared_type_reference("t0"), .required = true}},
                       .dispatch_policy = "framework",
                       .payload_contract = "strata.action-payload/command.execute@1",
                       .summary = "Execute a registered command"},
        DeclaredAction{
            .id = "environment.set",
            .parameters =
                {DeclaredParameter{.name = "density", .type = declared_type_reference("t1")},
                 DeclaredParameter{.name = "reducedMotion", .type = declared_type_reference("t2")},
                 DeclaredParameter{.name = "safeLeft", .type = declared_type_reference("t3")},
                 DeclaredParameter{.name = "safeTop", .type = declared_type_reference("t3")},
                 DeclaredParameter{.name = "safeRight", .type = declared_type_reference("t3")},
                 DeclaredParameter{.name = "safeBottom", .type = declared_type_reference("t3")}},
            .dispatch_policy = "framework",
            .payload_contract = "strata.action-payload/environment.set@1",
            .summary = "Set declarative environment preferences"},
        DeclaredAction{.id = "focus.clear",
                       .parameters = {},
                       .dispatch_policy = "framework",
                       .payload_contract = "strata.action-payload/focus.clear@1",
                       .summary = "Clear surface focus"},
        DeclaredAction{.id = "focus.request",
                       .parameters = {DeclaredParameter{
                           .name = "key", .type = declared_type_reference("t4"), .required = true}},
                       .dispatch_policy = "framework",
                       .payload_contract = "strata.action-payload/focus.request@1",
                       .summary = "Request focus for a keyed node"},
        DeclaredAction{.id = "form-submit",
                       .parameters = {},
                       .dispatch_policy = "optional",
                       .payload_contract = "no payload",
                       .summary = "Observe the built-in form-submit interaction"},
        DeclaredAction{.id = "form.submit",
                       .parameters = {DeclaredParameter{
                           .name = "key", .type = declared_type_reference("t4"), .required = true}},
                       .dispatch_policy = "framework",
                       .payload_contract = "strata.action-payload/form.submit@1",
                       .summary = "Submit a keyed form"},
        DeclaredAction{.id = "form.validate",
                       .parameters = {DeclaredParameter{.name = "key",
                                                        .type = declared_type_reference("t4"),
                                                        .required = true},
                                      DeclaredParameter{.name = "focusFirstInvalid",
                                                        .type = declared_type_reference("t2")},
                                      DeclaredParameter{.name = "notify",
                                                        .type = declared_type_reference("t2")}},
                       .dispatch_policy = "framework",
                       .payload_contract = "strata.action-payload/form.validate@1",
                       .summary = "Validate a keyed form"},
        DeclaredAction{.id = "layer.pop",
                       .parameters = {DeclaredParameter{.name = "transition",
                                                        .type = declared_type_reference("t5"),
                                                        .nullable = true}},
                       .dispatch_policy = "framework",
                       .payload_contract = "strata.action-payload/layer.pop@1",
                       .summary = "Pop the active screen"},
        DeclaredAction{.id = "layer.push",
                       .parameters = {DeclaredParameter{.name = "name",
                                                        .type = declared_type_reference("t0"),
                                                        .required = true},
                                      DeclaredParameter{.name = "transition",
                                                        .type = declared_type_reference("t5"),
                                                        .nullable = true}},
                       .dispatch_policy = "framework",
                       .payload_contract = "strata.action-payload/layer.push@1",
                       .summary = "Push a registered screen"},
        DeclaredAction{.id = "layer.replace",
                       .parameters = {DeclaredParameter{.name = "name",
                                                        .type = declared_type_reference("t0"),
                                                        .required = true},
                                      DeclaredParameter{.name = "transition",
                                                        .type = declared_type_reference("t5"),
                                                        .nullable = true}},
                       .dispatch_policy = "framework",
                       .payload_contract = "strata.action-payload/layer.replace@1",
                       .summary = "Replace with a registered screen"},
        DeclaredAction{.id = "modal-dismiss",
                       .parameters = {},
                       .dispatch_policy = "optional",
                       .payload_contract = "no payload",
                       .summary = "Observe the built-in modal-dismiss interaction"},
        DeclaredAction{.id = "notification.raise",
                       .parameters = {DeclaredParameter{.name = "message",
                                                        .type = declared_type_reference("t0"),
                                                        .required = true},
                                      DeclaredParameter{.name = "severity",
                                                        .type = declared_type_reference("t6")},
                                      DeclaredParameter{.name = "persistent",
                                                        .type = declared_type_reference("t2")},
                                      DeclaredParameter{.name = "timeoutMillis",
                                                        .type = declared_type_reference("t3"),
                                                        .nullable = true}},
                       .dispatch_policy = "framework",
                       .payload_contract = "strata.action-payload/notification.raise@1",
                       .summary = "Raise a passive notification"},
        DeclaredAction{.id = "overlay.hide",
                       .parameters = {DeclaredParameter{.name = "name",
                                                        .type = declared_type_reference("t0"),
                                                        .required = true},
                                      DeclaredParameter{.name = "transition",
                                                        .type = declared_type_reference("t5"),
                                                        .nullable = true}},
                       .dispatch_policy = "framework",
                       .payload_contract = "strata.action-payload/overlay.hide@1",
                       .summary = "Hide a registered overlay"},
        DeclaredAction{.id = "overlay.show",
                       .parameters = {DeclaredParameter{.name = "name",
                                                        .type = declared_type_reference("t0"),
                                                        .required = true},
                                      DeclaredParameter{.name = "transition",
                                                        .type = declared_type_reference("t5"),
                                                        .nullable = true}},
                       .dispatch_policy = "framework",
                       .payload_contract = "strata.action-payload/overlay.show@1",
                       .summary = "Show a registered overlay"},
        DeclaredAction{.id = "palette.set",
                       .parameters = {DeclaredParameter{.name = "key",
                                                        .type = declared_type_reference("t4"),
                                                        .nullable = true},
                                      DeclaredParameter{.name = "open",
                                                        .type = declared_type_reference("t2")}},
                       .dispatch_policy = "framework",
                       .payload_contract = "strata.action-payload/palette.set@1",
                       .summary = "Open or close a command palette"},
        DeclaredAction{
            .id = "reveal.request",
            .parameters =
                {DeclaredParameter{
                     .name = "key", .type = declared_type_reference("t4"), .required = true},
                 DeclaredParameter{
                     .name = "scroll", .type = declared_type_reference("t4"), .nullable = true},
                 DeclaredParameter{.name = "focus", .type = declared_type_reference("t2")},
                 DeclaredParameter{.name = "padding", .type = declared_type_reference("t3")}},
            .dispatch_policy = "framework",
            .payload_contract = "strata.action-payload/reveal.request@1",
            .summary = "Reveal a keyed node after reconciliation and layout"},
        DeclaredAction{.id = "split-change",
                       .parameters = {},
                       .dispatch_policy = "optional",
                       .payload_contract = "no payload",
                       .summary = "Observe the built-in split-change interaction"},
        DeclaredAction{
            .id = "state.adjust",
            .parameters =
                {DeclaredParameter{
                     .name = "name", .type = declared_type_reference("t0"), .required = true},
                 DeclaredParameter{
                     .name = "amount", .type = declared_type_reference("t3"), .required = true},
                 DeclaredParameter{.name = "undoLabel", .type = declared_type_reference("t0")},
                 DeclaredParameter{.name = "undoCoalesce", .type = declared_type_reference("t0")}},
            .dispatch_policy = "framework",
            .payload_contract = "strata.action-payload/state.adjust@1",
            .summary = "Adjust a declarative retained-state slot"},
        DeclaredAction{.id = "state.listAppend",
                       .parameters = {DeclaredParameter{.name = "name",
                                                        .type = declared_type_reference("t0"),
                                                        .required = true},
                                      DeclaredParameter{.name = "value",
                                                        .type = declared_type_reference("t7"),
                                                        .required = true,
                                                        .nullable = true},
                                      DeclaredParameter{.name = "undoLabel",
                                                        .type = declared_type_reference("t0")},
                                      DeclaredParameter{.name = "undoCoalesce",
                                                        .type = declared_type_reference("t0")}},
                       .dispatch_policy = "framework",
                       .payload_contract = "strata.action-payload/state.listAppend@1",
                       .summary = "Append to declarative list state"},
        DeclaredAction{.id = "state.listClear",
                       .parameters = {DeclaredParameter{.name = "name",
                                                        .type = declared_type_reference("t0"),
                                                        .required = true},
                                      DeclaredParameter{.name = "undoLabel",
                                                        .type = declared_type_reference("t0")},
                                      DeclaredParameter{.name = "undoCoalesce",
                                                        .type = declared_type_reference("t0")}},
                       .dispatch_policy = "framework",
                       .payload_contract = "strata.action-payload/state.listClear@1",
                       .summary = "Clear declarative list state"},
        DeclaredAction{.id = "state.listInsert",
                       .parameters = {DeclaredParameter{.name = "name",
                                                        .type = declared_type_reference("t0"),
                                                        .required = true},
                                      DeclaredParameter{.name = "index",
                                                        .type = declared_type_reference("t3"),
                                                        .required = true},
                                      DeclaredParameter{.name = "value",
                                                        .type = declared_type_reference("t7"),
                                                        .required = true,
                                                        .nullable = true},
                                      DeclaredParameter{.name = "undoLabel",
                                                        .type = declared_type_reference("t0")},
                                      DeclaredParameter{.name = "undoCoalesce",
                                                        .type = declared_type_reference("t0")}},
                       .dispatch_policy = "framework",
                       .payload_contract = "strata.action-payload/state.listInsert@1",
                       .summary = "Insert into declarative list state"},
        DeclaredAction{.id = "state.listRemoveAt",
                       .parameters = {DeclaredParameter{.name = "name",
                                                        .type = declared_type_reference("t0"),
                                                        .required = true},
                                      DeclaredParameter{.name = "index",
                                                        .type = declared_type_reference("t3"),
                                                        .required = true},
                                      DeclaredParameter{.name = "undoLabel",
                                                        .type = declared_type_reference("t0")},
                                      DeclaredParameter{.name = "undoCoalesce",
                                                        .type = declared_type_reference("t0")}},
                       .dispatch_policy = "framework",
                       .payload_contract = "strata.action-payload/state.listRemoveAt@1",
                       .summary = "Remove an index from declarative list state"},
        DeclaredAction{.id = "state.listRemoveValue",
                       .parameters = {DeclaredParameter{.name = "name",
                                                        .type = declared_type_reference("t0"),
                                                        .required = true},
                                      DeclaredParameter{.name = "value",
                                                        .type = declared_type_reference("t7"),
                                                        .required = true,
                                                        .nullable = true},
                                      DeclaredParameter{.name = "undoLabel",
                                                        .type = declared_type_reference("t0")},
                                      DeclaredParameter{.name = "undoCoalesce",
                                                        .type = declared_type_reference("t0")}},
                       .dispatch_policy = "framework",
                       .payload_contract = "strata.action-payload/state.listRemoveValue@1",
                       .summary = "Remove a value from declarative list state"},
        DeclaredAction{.id = "state.listToggle",
                       .parameters = {DeclaredParameter{.name = "name",
                                                        .type = declared_type_reference("t0"),
                                                        .required = true},
                                      DeclaredParameter{.name = "value",
                                                        .type = declared_type_reference("t7"),
                                                        .required = true,
                                                        .nullable = true},
                                      DeclaredParameter{.name = "undoLabel",
                                                        .type = declared_type_reference("t0")},
                                      DeclaredParameter{.name = "undoCoalesce",
                                                        .type = declared_type_reference("t0")}},
                       .dispatch_policy = "framework",
                       .payload_contract = "strata.action-payload/state.listToggle@1",
                       .summary = "Toggle membership in declarative list state"},
        DeclaredAction{.id = "state.recordSet",
                       .parameters = {DeclaredParameter{.name = "name",
                                                        .type = declared_type_reference("t0"),
                                                        .required = true},
                                      DeclaredParameter{.name = "field",
                                                        .type = declared_type_reference("t0"),
                                                        .required = true},
                                      DeclaredParameter{.name = "value",
                                                        .type = declared_type_reference("t7"),
                                                        .required = true,
                                                        .nullable = true},
                                      DeclaredParameter{.name = "undoLabel",
                                                        .type = declared_type_reference("t0")},
                                      DeclaredParameter{.name = "undoCoalesce",
                                                        .type = declared_type_reference("t0")}},
                       .dispatch_policy = "framework",
                       .payload_contract = "strata.action-payload/state.recordSet@1",
                       .summary = "Set a declarative record field"},
        DeclaredAction{.id = "state.reset",
                       .parameters = {DeclaredParameter{.name = "name",
                                                        .type = declared_type_reference("t0"),
                                                        .required = true},
                                      DeclaredParameter{.name = "undoLabel",
                                                        .type = declared_type_reference("t0")},
                                      DeclaredParameter{.name = "undoCoalesce",
                                                        .type = declared_type_reference("t0")}},
                       .dispatch_policy = "framework",
                       .payload_contract = "strata.action-payload/state.reset@1",
                       .summary = "Reset a declarative retained-state slot"},
        DeclaredAction{.id = "state.set",
                       .parameters = {DeclaredParameter{.name = "name",
                                                        .type = declared_type_reference("t0"),
                                                        .required = true},
                                      DeclaredParameter{.name = "value",
                                                        .type = declared_type_reference("t7"),
                                                        .required = true,
                                                        .nullable = true},
                                      DeclaredParameter{.name = "undoLabel",
                                                        .type = declared_type_reference("t0")},
                                      DeclaredParameter{.name = "undoCoalesce",
                                                        .type = declared_type_reference("t0")}},
                       .dispatch_policy = "framework",
                       .payload_contract = "strata.action-payload/state.set@1",
                       .summary = "Assign a declarative retained-state slot"},
        DeclaredAction{
            .id = "state.setFromEvent",
            .parameters =
                {DeclaredParameter{
                     .name = "name", .type = declared_type_reference("t0"), .required = true},
                 DeclaredParameter{.name = "undoLabel", .type = declared_type_reference("t0")},
                 DeclaredParameter{.name = "undoCoalesce", .type = declared_type_reference("t0")}},
            .dispatch_policy = "framework",
            .payload_contract = "strata.action-payload/state.setFromEvent@1",
            .summary = "Assign a declarative retained-state slot from the emitted widget event"},
        DeclaredAction{.id = "state.toggle",
                       .parameters = {DeclaredParameter{.name = "name",
                                                        .type = declared_type_reference("t0"),
                                                        .required = true},
                                      DeclaredParameter{.name = "undoLabel",
                                                        .type = declared_type_reference("t0")},
                                      DeclaredParameter{.name = "undoCoalesce",
                                                        .type = declared_type_reference("t0")}},
                       .dispatch_policy = "framework",
                       .payload_contract = "strata.action-payload/state.toggle@1",
                       .summary = "Toggle a declarative retained-state slot"},
        DeclaredAction{.id = "text-edit",
                       .parameters = {},
                       .dispatch_policy = "optional",
                       .payload_contract = "no payload",
                       .summary = "Observe the built-in text-edit interaction"},
        DeclaredAction{.id = "tree.collapse",
                       .parameters = {DeclaredParameter{.name = "tree",
                                                        .type = declared_type_reference("t4"),
                                                        .required = true},
                                      DeclaredParameter{.name = "item",
                                                        .type = declared_type_reference("t4"),
                                                        .required = true}},
                       .dispatch_policy = "framework",
                       .payload_contract = "strata.action-payload/tree.collapse@1",
                       .summary = "Collapse an item in a keyed tree"},
        DeclaredAction{.id = "tree.expand",
                       .parameters = {DeclaredParameter{.name = "tree",
                                                        .type = declared_type_reference("t4"),
                                                        .required = true},
                                      DeclaredParameter{.name = "item",
                                                        .type = declared_type_reference("t4"),
                                                        .required = true}},
                       .dispatch_policy = "framework",
                       .payload_contract = "strata.action-payload/tree.expand@1",
                       .summary = "Expand an item in a keyed tree"},
        DeclaredAction{.id = "tree.reveal",
                       .parameters = {DeclaredParameter{.name = "tree",
                                                        .type = declared_type_reference("t4"),
                                                        .required = true},
                                      DeclaredParameter{.name = "item",
                                                        .type = declared_type_reference("t4"),
                                                        .required = true}},
                       .dispatch_policy = "framework",
                       .payload_contract = "strata.action-payload/tree.reveal@1",
                       .summary = "Expand ancestors and reveal an item in a keyed tree"},
        DeclaredAction{.id = "tree.toggle",
                       .parameters = {DeclaredParameter{.name = "tree",
                                                        .type = declared_type_reference("t4"),
                                                        .required = true},
                                      DeclaredParameter{.name = "item",
                                                        .type = declared_type_reference("t4"),
                                                        .required = true}},
                       .dispatch_policy = "framework",
                       .payload_contract = "strata.action-payload/tree.toggle@1",
                       .summary = "Toggle an item in a keyed tree"},
    };
}

} // namespace strata::compiler
