#include "compiler/builtin_catalog_internal.hpp"

namespace strata::compiler {

void add_builtin_primitive_widgets(BuiltinCatalog& catalog) {
    catalog.widgets.insert(
        catalog.widgets.end(),
        {
            DeclaredWidget{
                .name = "Button",
                .parameters =
                    {DeclaredParameter{
                         .name = "label", .type = declared_type_reference("t0"), .required = true},
                     DeclaredParameter{.name = "enabled", .type = declared_type_reference("t2")},
                     DeclaredParameter{.name = "presentationTemplate",
                                       .type = declared_type_reference("t175")},
                     DeclaredParameter{.name = "onClick", .type = declared_type_reference("t36")},
                     DeclaredParameter{.name = "command",
                                       .type = declared_type_reference("t0"),
                                       .nullable = true}},
                .parameter_order = {"label",
                                    "key",
                                    "enabled",
                                    "presentationTemplate",
                                    "layout",
                                    "variant",
                                    "style",
                                    "visualStyle",
                                    "effect",
                                    "material",
                                    "transition",
                                    "enter",
                                    "exit",
                                    "move",
                                    "motions",
                                    "animateChanges",
                                    "animateContentSize",
                                    "disclosure",
                                    "contentKey",
                                    "contentTransition",
                                    "contentTransitionMode",
                                    "stagger",
                                    "semantics",
                                    "textStyle",
                                    "textVisualStyle",
                                    "animation",
                                    "onClick",
                                    "command",
                                    "behaviors"},
                .bindings = {},
                .events = {DeclaredWidgetEvent{
                    .name = "activation",
                    .callback_parameter = "onClick",
                    .description = "Emitted after pointer or keyboard activation."}},
                .retained_state = {}},
            DeclaredWidget{
                .name = "ContextMenu",
                .parameters =
                    {DeclaredParameter{
                         .name = "items", .type = declared_type_reference("t52"), .required = true},
                     DeclaredParameter{.name = "menuWidth", .type = declared_type_reference("t3")},
                     DeclaredParameter{.name = "rowHeight", .type = declared_type_reference("t3")},
                     DeclaredParameter{.name = "triggerTemplate",
                                       .type = declared_type_reference("t163")},
                     DeclaredParameter{.name = "popupTemplate",
                                       .type = declared_type_reference("t164")},
                     DeclaredParameter{.name = "itemTemplate",
                                       .type = declared_type_reference("t165")},
                     DeclaredParameter{.name = "onSelect", .type = declared_type_reference("t36")}},
                .parameter_order = {"items",
                                    "key",
                                    "menuWidth",
                                    "rowHeight",
                                    "triggerTemplate",
                                    "popupTemplate",
                                    "itemTemplate",
                                    "layout",
                                    "variant",
                                    "style",
                                    "visualStyle",
                                    "effect",
                                    "material",
                                    "transition",
                                    "enter",
                                    "exit",
                                    "move",
                                    "motions",
                                    "animateChanges",
                                    "animateContentSize",
                                    "disclosure",
                                    "contentKey",
                                    "contentTransition",
                                    "contentTransitionMode",
                                    "stagger",
                                    "semantics",
                                    "textStyle",
                                    "textVisualStyle",
                                    "onSelect",
                                    "animation",
                                    "behaviors"},
                .bindings = {},
                .events = {DeclaredWidgetEvent{.name = "item selection",
                                               .callback_parameter = "onSelect",
                                               .description =
                                                   "Carries the selected context-menu item id."}},
                .retained_state = {DeclaredRetainedState{
                    .name = "popup",
                    .description = "Open state, active menu path, and pointer anchor."}},
                .allows_children = true},
            DeclaredWidget{
                .name = "Draw",
                .parameters = {DeclaredParameter{
                    .name = "shapes", .type = declared_type_reference("t153"), .required = true}},
                .parameter_order = {"shapes",
                                    "key",
                                    "layout",
                                    "variant",
                                    "style",
                                    "visualStyle",
                                    "effect",
                                    "material",
                                    "transition",
                                    "enter",
                                    "exit",
                                    "move",
                                    "motions",
                                    "animateChanges",
                                    "animateContentSize",
                                    "disclosure",
                                    "contentKey",
                                    "contentTransition",
                                    "contentTransitionMode",
                                    "stagger",
                                    "semantics",
                                    "textStyle",
                                    "textVisualStyle",
                                    "animation",
                                    "behaviors"},
                .bindings = {},
                .events = {},
                .retained_state = {}},
            DeclaredWidget{
                .name = "Grid",
                .parameters = {DeclaredParameter{.name = "columns",
                                                 .type = declared_type_reference("t112"),
                                                 .required = true},
                               DeclaredParameter{.name = "rows",
                                                 .type = declared_type_reference("t112")}},
                .parameter_order = {"columns",
                                    "rows",
                                    "key",
                                    "layout",
                                    "variant",
                                    "style",
                                    "visualStyle",
                                    "effect",
                                    "material",
                                    "transition",
                                    "enter",
                                    "exit",
                                    "move",
                                    "motions",
                                    "animateChanges",
                                    "animateContentSize",
                                    "disclosure",
                                    "contentKey",
                                    "contentTransition",
                                    "contentTransitionMode",
                                    "stagger",
                                    "semantics",
                                    "textStyle",
                                    "textVisualStyle",
                                    "animation",
                                    "behaviors"},
                .bindings = {},
                .events = {},
                .retained_state = {},
                .allows_children = true},
            DeclaredWidget{.name = "Image",
                           .parameters = {DeclaredParameter{.name = "image",
                                                            .type = declared_type_reference("t66"),
                                                            .required = true},
                                          DeclaredParameter{.name = "source",
                                                            .type = declared_type_reference("t67")},
                                          DeclaredParameter{.name = "tint",
                                                            .type = declared_type_reference("t8")}},
                           .parameter_order =
                               {"image",
                                "key",
                                "source",
                                "tint",
                                "layout",
                                "variant",
                                "style",
                                "visualStyle",
                                "effect",
                                "material",
                                "transition",
                                "enter",
                                "exit",
                                "move",
                                "motions",
                                "animateChanges",
                                "animateContentSize",
                                "disclosure",
                                "contentKey",
                                "contentTransition",
                                "contentTransitionMode",
                                "stagger",
                                "semantics",
                                "textStyle",
                                "textVisualStyle",
                                "animation",
                                "behaviors"},
                           .bindings = {},
                           .events = {},
                           .retained_state = {}},
            DeclaredWidget{
                .name = "List",
                .parameters =
                    {DeclaredParameter{.name = "selectedKey",
                                       .type = declared_type_reference("t4"),
                                       .nullable = true},
                     DeclaredParameter{.name = "onSelect", .type = declared_type_reference("t36")},
                     DeclaredParameter{.name = "bind", .type = declared_type_reference("t7")}},
                .parameter_order = {"key",
                                    "selectedKey",
                                    "layout",
                                    "variant",
                                    "style",
                                    "visualStyle",
                                    "effect",
                                    "material",
                                    "transition",
                                    "enter",
                                    "exit",
                                    "move",
                                    "motions",
                                    "animateChanges",
                                    "animateContentSize",
                                    "disclosure",
                                    "contentKey",
                                    "contentTransition",
                                    "contentTransitionMode",
                                    "stagger",
                                    "semantics",
                                    "onSelect",
                                    "bind",
                                    "textStyle",
                                    "textVisualStyle",
                                    "animation",
                                    "behaviors"},
                .bindings = {DeclaredWidgetBinding{.shorthand_parameter = "bind",
                                                   .value_parameter = "selectedKey",
                                                   .event_parameter = "onSelect"}},
                .events = {DeclaredWidgetEvent{.name = "selection change",
                                               .callback_parameter = "onSelect",
                                               .description =
                                                   "Carries the key of the selected child."}},
                .retained_state = {DeclaredRetainedState{
                    .name = "selectedKey", .description = "Uncontrolled selected child key."}},
                .allows_children = true},
            DeclaredWidget{
                .name = "Menu",
                .parameters =
                    {DeclaredParameter{.name = "label",
                                       .type = declared_type_reference("t0"),
                                       .required = true},
                     DeclaredParameter{.name = "items",
                                       .type = declared_type_reference("t52"),
                                       .required = true},
                     DeclaredParameter{
                         .name = "open", .type = declared_type_reference("t2"), .nullable = true},
                     DeclaredParameter{.name = "defaultOpen",
                                       .type = declared_type_reference("t2")},
                     DeclaredParameter{.name = "menuWidth", .type = declared_type_reference("t3")},
                     DeclaredParameter{.name = "rowHeight", .type = declared_type_reference("t3")},
                     DeclaredParameter{.name = "triggerTemplate",
                                       .type = declared_type_reference("t163")},
                     DeclaredParameter{.name = "popupTemplate",
                                       .type = declared_type_reference("t164")},
                     DeclaredParameter{.name = "itemTemplate",
                                       .type = declared_type_reference("t165")},
                     DeclaredParameter{.name = "onSelect", .type = declared_type_reference("t36")}},
                .parameter_order = {"label",
                                    "items",
                                    "key",
                                    "open",
                                    "defaultOpen",
                                    "menuWidth",
                                    "rowHeight",
                                    "triggerTemplate",
                                    "popupTemplate",
                                    "itemTemplate",
                                    "layout",
                                    "variant",
                                    "style",
                                    "visualStyle",
                                    "effect",
                                    "material",
                                    "transition",
                                    "enter",
                                    "exit",
                                    "move",
                                    "motions",
                                    "animateChanges",
                                    "animateContentSize",
                                    "disclosure",
                                    "contentKey",
                                    "contentTransition",
                                    "contentTransitionMode",
                                    "stagger",
                                    "semantics",
                                    "textStyle",
                                    "textVisualStyle",
                                    "onSelect",
                                    "animation",
                                    "behaviors"},
                .bindings = {},
                .events = {DeclaredWidgetEvent{.name = "item selection",
                                               .callback_parameter = "onSelect",
                                               .description =
                                                   "Carries the selected menu item id."}},
                .retained_state = {DeclaredRetainedState{
                    .name = "popup",
                    .description = "Uncontrolled open state, active menu path, and popup anchor "
                                   "initialized by `defaultOpen`."}}},
            DeclaredWidget{
                .name = "Panel",
                .parameters = {DeclaredParameter{
                    .name = "movement", .type = declared_type_reference("t53"), .nullable = true}},
                .parameter_order = {"key",
                                    "layout",
                                    "variant",
                                    "style",
                                    "visualStyle",
                                    "effect",
                                    "material",
                                    "transition",
                                    "enter",
                                    "exit",
                                    "move",
                                    "motions",
                                    "animateChanges",
                                    "animateContentSize",
                                    "disclosure",
                                    "contentKey",
                                    "contentTransition",
                                    "contentTransitionMode",
                                    "stagger",
                                    "semantics",
                                    "movement",
                                    "textStyle",
                                    "textVisualStyle",
                                    "animation",
                                    "behaviors"},
                .bindings = {},
                .events = {},
                .retained_state = {DeclaredRetainedState{
                    .name = "movementOffset",
                    .description = "Current movable-panel offset and active movement gesture."}},
                .allows_children = true},
            DeclaredWidget{
                .name = "RichText",
                .parameters =
                    {DeclaredParameter{.name = "spans",
                                       .type = declared_type_reference("t58"),
                                       .required = true},
                     DeclaredParameter{.name = "wrapWidth",
                                       .type = declared_type_reference("t3"),
                                       .nullable = true},
                     DeclaredParameter{.name = "wrapMode", .type = declared_type_reference("t69")},
                     DeclaredParameter{.name = "overflow", .type = declared_type_reference("t55")},
                     DeclaredParameter{.name = "maxLines",
                                       .type = declared_type_reference("t3"),
                                       .nullable = true},
                     DeclaredParameter{.name = "alignment", .type = declared_type_reference("t65")},
                     DeclaredParameter{.name = "selectable", .type = declared_type_reference("t2")},
                     DeclaredParameter{.name = "selectionContainer",
                                       .type = declared_type_reference("t0"),
                                       .nullable = true}},
                .parameter_order =
                    {"spans",
                     "key",
                     "layout",
                     "variant",
                     "style",
                     "visualStyle",
                     "effect",
                     "material",
                     "transition",
                     "enter",
                     "exit",
                     "move",
                     "motions",
                     "animateChanges",
                     "animateContentSize",
                     "disclosure",
                     "contentKey",
                     "contentTransition",
                     "contentTransitionMode",
                     "stagger",
                     "semantics",
                     "textStyle",
                     "textVisualStyle",
                     "wrapWidth",
                     "wrapMode",
                     "overflow",
                     "maxLines",
                     "alignment",
                     "selectable",
                     "selectionContainer",
                     "animation",
                     "behaviors"},
                .bindings = {},
                .events = {},
                .retained_state = {}},
            DeclaredWidget{
                .name = "Section",
                .parameters =
                    {DeclaredParameter{.name = "label",
                                       .type = declared_type_reference("t0"),
                                       .required = true},
                     DeclaredParameter{.name = "expanded",
                                       .type = declared_type_reference("t2"),
                                       .nullable = true},
                     DeclaredParameter{.name = "defaultExpanded",
                                       .type = declared_type_reference("t2")},
                     DeclaredParameter{.name = "headerHeight",
                                       .type = declared_type_reference("t3")},
                     DeclaredParameter{.name = "contentPadding",
                                       .type = declared_type_reference("t61")},
                     DeclaredParameter{.name = "contentGap",
                                       .type = declared_type_reference("t61")},
                     DeclaredParameter{.name = "onChange", .type = declared_type_reference("t36")},
                     DeclaredParameter{.name = "bind", .type = declared_type_reference("t7")}},
                .parameter_order =
                    {"label",
                     "key",
                     "expanded",
                     "defaultExpanded",
                     "headerHeight",
                     "contentPadding",
                     "contentGap",
                     "layout",
                     "variant",
                     "style",
                     "visualStyle",
                     "effect",
                     "material",
                     "transition",
                     "enter",
                     "exit",
                     "move",
                     "motions",
                     "animateChanges",
                     "animateContentSize",
                     "disclosure",
                     "contentKey",
                     "contentTransition",
                     "contentTransitionMode",
                     "stagger",
                     "semantics",
                     "onChange",
                     "bind",
                     "textStyle",
                     "textVisualStyle",
                     "animation",
                     "behaviors"},
                .bindings = {DeclaredWidgetBinding{.shorthand_parameter = "bind",
                                                   .value_parameter = "expanded",
                                                   .event_parameter = "onChange"}},
                .events = {DeclaredWidgetEvent{.name = "expanded change",
                                               .callback_parameter = "onChange",
                                               .description =
                                                   "Carries the requested expanded state."}},
                .retained_state = {DeclaredRetainedState{
                    .name = "expanded",
                    .description =
                        "Uncontrolled disclosure state initialized by `defaultExpanded`."}},
                .allows_children = true},
            DeclaredWidget{
                .name = "Slot",
                .parameters = {DeclaredParameter{.name = "name",
                                                 .type = declared_type_reference("t0"),
                                                 .required = true},
                               DeclaredParameter{.name = "required",
                                                 .type = declared_type_reference("t2")}},
                .parameter_order = {"name",
                                    "required",
                                    "key",
                                    "layout",
                                    "variant",
                                    "style",
                                    "visualStyle",
                                    "effect",
                                    "material",
                                    "transition",
                                    "enter",
                                    "exit",
                                    "move",
                                    "motions",
                                    "animateChanges",
                                    "animateContentSize",
                                    "disclosure",
                                    "contentKey",
                                    "contentTransition",
                                    "contentTransitionMode",
                                    "stagger",
                                    "semantics",
                                    "textStyle",
                                    "textVisualStyle",
                                    "animation",
                                    "behaviors"},
                .bindings = {},
                .events = {},
                .retained_state = {},
                .allows_children = true},
            DeclaredWidget{.name = "StatusBar",
                           .parameters = {DeclaredParameter{.name = "showCommandFeedback",
                                                            .type = declared_type_reference("t2")}},
                           .parameter_order = {"key",
                                               "showCommandFeedback",
                                               "layout",
                                               "variant",
                                               "style",
                                               "visualStyle",
                                               "effect",
                                               "material",
                                               "transition",
                                               "enter",
                                               "exit",
                                               "move",
                                               "motions",
                                               "animateChanges",
                                               "animateContentSize",
                                               "disclosure",
                                               "contentKey",
                                               "contentTransition",
                                               "contentTransitionMode",
                                               "stagger",
                                               "semantics",
                                               "textStyle",
                                               "textVisualStyle",
                                               "animation",
                                               "behaviors"},
                           .bindings = {},
                           .events = {},
                           .retained_state = {},
                           .allows_children = true},
            DeclaredWidget{
                .name = "Text",
                .parameters =
                    {DeclaredParameter{
                         .name = "text", .type = declared_type_reference("t0"), .required = true},
                     DeclaredParameter{.name = "wrapWidth",
                                       .type = declared_type_reference("t3"),
                                       .nullable = true},
                     DeclaredParameter{.name = "wrapMode", .type = declared_type_reference("t69")},
                     DeclaredParameter{.name = "overflow", .type = declared_type_reference("t55")},
                     DeclaredParameter{.name = "maxLines",
                                       .type = declared_type_reference("t3"),
                                       .nullable = true},
                     DeclaredParameter{.name = "alignment", .type = declared_type_reference("t65")},
                     DeclaredParameter{.name = "selectable", .type = declared_type_reference("t2")},
                     DeclaredParameter{.name = "selectionContainer",
                                       .type = declared_type_reference("t0"),
                                       .nullable = true}},
                .parameter_order = {"text",
                                    "key",
                                    "layout",
                                    "variant",
                                    "style",
                                    "visualStyle",
                                    "effect",
                                    "material",
                                    "transition",
                                    "enter",
                                    "exit",
                                    "move",
                                    "motions",
                                    "animateChanges",
                                    "animateContentSize",
                                    "disclosure",
                                    "contentKey",
                                    "contentTransition",
                                    "contentTransitionMode",
                                    "stagger",
                                    "semantics",
                                    "textStyle",
                                    "textVisualStyle",
                                    "wrapWidth",
                                    "wrapMode",
                                    "overflow",
                                    "maxLines",
                                    "alignment",
                                    "selectable",
                                    "selectionContainer",
                                    "animation",
                                    "behaviors"},
                .bindings = {},
                .events = {},
                .retained_state = {}},
            DeclaredWidget{.name = "ThemeScope",
                           .parameters = {DeclaredParameter{.name = "theme",
                                                            .type = declared_type_reference("t0"),
                                                            .required = true}},
                           .parameter_order =
                               {"theme",
                                "key",
                                "layout",
                                "variant",
                                "style",
                                "visualStyle",
                                "effect",
                                "material",
                                "transition",
                                "enter",
                                "exit",
                                "move",
                                "motions",
                                "animateChanges",
                                "animateContentSize",
                                "disclosure",
                                "contentKey",
                                "contentTransition",
                                "contentTransitionMode",
                                "stagger",
                                "semantics",
                                "textStyle",
                                "textVisualStyle",
                                "animation",
                                "behaviors"},
                           .bindings = {},
                           .events = {},
                           .retained_state = {},
                           .allows_children = true},
            DeclaredWidget{
                .name = "Tooltip",
                .parameters =
                    {DeclaredParameter{
                         .name = "text", .type = declared_type_reference("t0"), .required = true},
                     DeclaredParameter{.name = "visible",
                                       .type = declared_type_reference("t2"),
                                       .nullable = true},
                     DeclaredParameter{.name = "showDelay", .type = declared_type_reference("t9")},
                     DeclaredParameter{.name = "hideDelay", .type = declared_type_reference("t9")},
                     DeclaredParameter{.name = "contentTemplate",
                                       .type = declared_type_reference("t166")}},
                .parameter_order = {"text",
                                    "key",
                                    "visible",
                                    "showDelay",
                                    "hideDelay",
                                    "contentTemplate",
                                    "layout",
                                    "variant",
                                    "style",
                                    "visualStyle",
                                    "effect",
                                    "material",
                                    "transition",
                                    "enter",
                                    "exit",
                                    "move",
                                    "motions",
                                    "animateChanges",
                                    "animateContentSize",
                                    "disclosure",
                                    "contentKey",
                                    "contentTransition",
                                    "contentTransitionMode",
                                    "stagger",
                                    "semantics",
                                    "textStyle",
                                    "textVisualStyle",
                                    "animation",
                                    "behaviors"},
                .bindings = {},
                .events = {},
                .retained_state = {},
                .allows_children = true},
        });
}

} // namespace strata::compiler
