#include "compiler/builtin_catalog_internal.hpp"

namespace strata::compiler {

void add_builtin_shell_widgets(BuiltinCatalog& catalog) {
    catalog.widgets.insert(
        catalog.widgets.end(),
        {
            DeclaredWidget{
                .name = "Banner",
                .parameters = {DeclaredParameter{.name = "message",
                                                 .type = declared_type_reference("t0"),
                                                 .required = true},
                               DeclaredParameter{.name = "severity",
                                                 .type = declared_type_reference("t111")},
                               DeclaredParameter{.name = "actionLabel",
                                                 .type = declared_type_reference("t0"),
                                                 .nullable = true},
                               DeclaredParameter{.name = "action",
                                                 .type = declared_type_reference("t36"),
                                                 .nullable = true},
                               DeclaredParameter{.name = "dismissible",
                                                 .type = declared_type_reference("t2")}},
                .parameter_order = {"message",
                                    "key",
                                    "severity",
                                    "actionLabel",
                                    "action",
                                    "dismissible",
                                    "layout",
                                    "variant",
                                    "style",
                                    "visualStyle",
                                    "effect",
                                    "material",
                                    "transition",
                                    "enter",
                                    "exit",
                                    "move",
                                    "motions",
                                    "animateChanges",
                                    "animateContentSize",
                                    "disclosure",
                                    "contentKey",
                                    "contentTransition",
                                    "contentTransitionMode",
                                    "stagger",
                                    "semantics",
                                    "textStyle",
                                    "textVisualStyle",
                                    "animation",
                                    "behaviors"},
                .bindings = {},
                .events = {DeclaredWidgetEvent{
                    .name = "activation",
                    .callback_parameter = "action",
                    .description = "Emitted when the optional banner action is activated."}},
                .retained_state = {DeclaredRetainedState{
                    .name = "dismissed",
                    .description = "Whether a dismissible banner has been explicitly closed."}}},
            DeclaredWidget{
                .name = "Breadcrumbs",
                .parameters = {DeclaredParameter{.name = "items",
                                                 .type = declared_type_reference("t39"),
                                                 .required = true},
                               DeclaredParameter{.name = "onSelect",
                                                 .type = declared_type_reference("t36")}},
                .parameter_order = {"items",
                                    "key",
                                    "layout",
                                    "variant",
                                    "style",
                                    "visualStyle",
                                    "effect",
                                    "material",
                                    "transition",
                                    "enter",
                                    "exit",
                                    "move",
                                    "motions",
                                    "animateChanges",
                                    "animateContentSize",
                                    "disclosure",
                                    "contentKey",
                                    "contentTransition",
                                    "contentTransitionMode",
                                    "stagger",
                                    "semantics",
                                    "textStyle",
                                    "textVisualStyle",
                                    "onSelect",
                                    "animation",
                                    "behaviors"},
                .bindings = {},
                .events = {DeclaredWidgetEvent{.name = "selection",
                                               .callback_parameter = "onSelect",
                                               .description =
                                                   "Carries the selected breadcrumb id."}},
                .retained_state = {}},
            DeclaredWidget{
                .name = "ChipInput",
                .parameters =
                    {DeclaredParameter{.name = "values",
                                       .type = declared_type_reference("t78"),
                                       .nullable = true},
                     DeclaredParameter{.name = "defaultValues",
                                       .type = declared_type_reference("t78")},
                     DeclaredParameter{.name = "placeholder",
                                       .type = declared_type_reference("t0")},
                     DeclaredParameter{.name = "maxChips", .type = declared_type_reference("t3")},
                     DeclaredParameter{.name = "enabled", .type = declared_type_reference("t2")},
                     DeclaredParameter{.name = "onChange", .type = declared_type_reference("t36")},
                     DeclaredParameter{.name = "bind", .type = declared_type_reference("t7")}},
                .parameter_order = {"values",
                                    "defaultValues",
                                    "placeholder",
                                    "maxChips",
                                    "enabled",
                                    "key",
                                    "layout",
                                    "variant",
                                    "style",
                                    "visualStyle",
                                    "effect",
                                    "material",
                                    "transition",
                                    "enter",
                                    "exit",
                                    "move",
                                    "motions",
                                    "animateChanges",
                                    "animateContentSize",
                                    "disclosure",
                                    "contentKey",
                                    "contentTransition",
                                    "contentTransitionMode",
                                    "stagger",
                                    "semantics",
                                    "textStyle",
                                    "textVisualStyle",
                                    "onChange",
                                    "bind",
                                    "animation",
                                    "behaviors"},
                .bindings = {DeclaredWidgetBinding{.shorthand_parameter = "bind",
                                                   .value_parameter = "values",
                                                   .event_parameter = "onChange"}},
                .events = {DeclaredWidgetEvent{.name = "values change",
                                               .callback_parameter = "onChange",
                                               .description = "Carries the complete token list."}},
                .retained_state = {DeclaredRetainedState{
                    .name = "values",
                    .description = "Uncontrolled token list, draft text, and active token."}}},
            DeclaredWidget{
                .name = "Command",
                .parameters =
                    {DeclaredParameter{.name = "id",
                                       .type = declared_type_reference("t0"),
                                       .required = true},
                     DeclaredParameter{.name = "label",
                                       .type = declared_type_reference("t0"),
                                       .required = true},
                     DeclaredParameter{.name = "action",
                                       .type = declared_type_reference("t36"),
                                       .required = true},
                     DeclaredParameter{.name = "category", .type = declared_type_reference("t0")},
                     DeclaredParameter{.name = "shortcut",
                                       .type = declared_type_reference("t0"),
                                       .nullable = true},
                     DeclaredParameter{
                         .name = "icon", .type = declared_type_reference("t66"), .nullable = true},
                     DeclaredParameter{
                         .name = "scope", .type = declared_type_reference("t4"), .nullable = true},
                     DeclaredParameter{.name = "enabled", .type = declared_type_reference("t2")},
                     DeclaredParameter{.name = "checked",
                                       .type = declared_type_reference("t2"),
                                       .nullable = true},
                     DeclaredParameter{.name = "acceptsRepeat",
                                       .type = declared_type_reference("t2")},
                     DeclaredParameter{.name = "priority", .type = declared_type_reference("t3")},
                     DeclaredParameter{.name = "allowedWhileModal",
                                       .type = declared_type_reference("t2")},
                     DeclaredParameter{.name = "allowedWhileTextEditing",
                                       .type = declared_type_reference("t2")}},
                .parameter_order = {"id",
                                    "label",
                                    "action",
                                    "category",
                                    "shortcut",
                                    "icon",
                                    "scope",
                                    "enabled",
                                    "checked",
                                    "acceptsRepeat",
                                    "priority",
                                    "allowedWhileModal",
                                    "allowedWhileTextEditing",
                                    "key",
                                    "layout",
                                    "variant",
                                    "style",
                                    "visualStyle",
                                    "effect",
                                    "material",
                                    "transition",
                                    "enter",
                                    "exit",
                                    "move",
                                    "motions",
                                    "animateChanges",
                                    "animateContentSize",
                                    "disclosure",
                                    "contentKey",
                                    "contentTransition",
                                    "contentTransitionMode",
                                    "stagger",
                                    "semantics",
                                    "textStyle",
                                    "textVisualStyle",
                                    "animation",
                                    "behaviors"},
                .bindings = {},
                .events = {DeclaredWidgetEvent{
                    .name = "command invocation",
                    .callback_parameter = "action",
                    .description = "Dispatched when any command surface invokes this command."}},
                .retained_state = {}},
            DeclaredWidget{
                .name = "CommandPalette",
                .parameters =
                    {DeclaredParameter{.name = "commands", .type = declared_type_reference("t78")},
                     DeclaredParameter{
                         .name = "items", .type = declared_type_reference("t60"), .nullable = true},
                     DeclaredParameter{.name = "placeholder",
                                       .type = declared_type_reference("t0")},
                     DeclaredParameter{.name = "maxVisibleRows",
                                       .type = declared_type_reference("t3")},
                     DeclaredParameter{.name = "rowHeight", .type = declared_type_reference("t3")},
                     DeclaredParameter{.name = "onSelect", .type = declared_type_reference("t36")}},
                .parameter_order = {"commands",
                                    "items",
                                    "key",
                                    "placeholder",
                                    "maxVisibleRows",
                                    "rowHeight",
                                    "layout",
                                    "variant",
                                    "style",
                                    "visualStyle",
                                    "effect",
                                    "material",
                                    "transition",
                                    "enter",
                                    "exit",
                                    "move",
                                    "motions",
                                    "animateChanges",
                                    "animateContentSize",
                                    "disclosure",
                                    "contentKey",
                                    "contentTransition",
                                    "contentTransitionMode",
                                    "stagger",
                                    "semantics",
                                    "textStyle",
                                    "textVisualStyle",
                                    "onSelect",
                                    "animation",
                                    "behaviors"},
                .bindings = {},
                .events = {DeclaredWidgetEvent{
                    .name = "picker selection",
                    .callback_parameter = "onSelect",
                    .description =
                        "Carries the id chosen from a custom quick-picker item source."}},
                .retained_state = {DeclaredRetainedState{
                    .name = "palette",
                    .description =
                        "Open state, query, active result, and windowed result range."}}},
            DeclaredWidget{
                .name = "Field",
                .parameters =
                    {DeclaredParameter{
                         .name = "name", .type = declared_type_reference("t0"), .required = true},
                     DeclaredParameter{
                         .name = "label", .type = declared_type_reference("t0"), .required = true},
                     DeclaredParameter{.name = "inputKey",
                                       .type = declared_type_reference("t4"),
                                       .required = true},
                     DeclaredParameter{.name = "help", .type = declared_type_reference("t0")},
                     DeclaredParameter{
                         .name = "error", .type = declared_type_reference("t0"), .nullable = true},
                     DeclaredParameter{.name = "required", .type = declared_type_reference("t2")},
                     DeclaredParameter{.name = "requiredMessage",
                                       .type = declared_type_reference("t0")},
                     DeclaredParameter{.name = "enabled", .type = declared_type_reference("t2")},
                     DeclaredParameter{.name = "readOnly", .type = declared_type_reference("t2")},
                     DeclaredParameter{.name = "minLength",
                                       .type = declared_type_reference("t3"),
                                       .nullable = true},
                     DeclaredParameter{.name = "minLengthMessage",
                                       .type = declared_type_reference("t0")},
                     DeclaredParameter{.name = "maxLength",
                                       .type = declared_type_reference("t3"),
                                       .nullable = true},
                     DeclaredParameter{.name = "maxLengthMessage",
                                       .type = declared_type_reference("t0")},
                     DeclaredParameter{
                         .name = "min", .type = declared_type_reference("t3"), .nullable = true},
                     DeclaredParameter{
                         .name = "max", .type = declared_type_reference("t3"), .nullable = true},
                     DeclaredParameter{.name = "rangeMessage",
                                       .type = declared_type_reference("t0")}},
                .parameter_order = {"name",
                                    "label",
                                    "inputKey",
                                    "key",
                                    "help",
                                    "error",
                                    "required",
                                    "requiredMessage",
                                    "enabled",
                                    "readOnly",
                                    "minLength",
                                    "minLengthMessage",
                                    "maxLength",
                                    "maxLengthMessage",
                                    "min",
                                    "max",
                                    "rangeMessage",
                                    "layout",
                                    "variant",
                                    "style",
                                    "visualStyle",
                                    "effect",
                                    "material",
                                    "transition",
                                    "enter",
                                    "exit",
                                    "move",
                                    "motions",
                                    "animateChanges",
                                    "animateContentSize",
                                    "disclosure",
                                    "contentKey",
                                    "contentTransition",
                                    "contentTransitionMode",
                                    "stagger",
                                    "semantics",
                                    "textStyle",
                                    "textVisualStyle",
                                    "animation",
                                    "behaviors"},
                .bindings = {},
                .events = {},
                .retained_state = {DeclaredRetainedState{
                    .name = "validation",
                    .description = "Dirty, touched, validated, and current derived-error state for "
                                   "the keyed field."}},
                .allows_children = true},
            DeclaredWidget{
                .name = "Form",
                .parameters = {DeclaredParameter{.name = "key",
                                                 .type = declared_type_reference("t4"),
                                                 .required = true},
                               DeclaredParameter{.name = "validateOnChange",
                                                 .type = declared_type_reference("t2")},
                               DeclaredParameter{.name = "validateOnBlur",
                                                 .type = declared_type_reference("t2")},
                               DeclaredParameter{.name = "validateOnSubmit",
                                                 .type = declared_type_reference("t2")},
                               DeclaredParameter{.name = "revalidateAfterFirstValidation",
                                                 .type = declared_type_reference("t2")},
                               DeclaredParameter{.name = "onSubmit",
                                                 .type = declared_type_reference("t36")}},
                .parameter_order = {"key",
                                    "validateOnChange",
                                    "validateOnBlur",
                                    "validateOnSubmit",
                                    "revalidateAfterFirstValidation",
                                    "onSubmit",
                                    "layout",
                                    "variant",
                                    "style",
                                    "visualStyle",
                                    "effect",
                                    "material",
                                    "transition",
                                    "enter",
                                    "exit",
                                    "move",
                                    "motions",
                                    "animateChanges",
                                    "animateContentSize",
                                    "disclosure",
                                    "contentKey",
                                    "contentTransition",
                                    "contentTransitionMode",
                                    "stagger",
                                    "semantics",
                                    "textStyle",
                                    "textVisualStyle",
                                    "animation",
                                    "behaviors"},
                .bindings = {},
                .events = {DeclaredWidgetEvent{.name = "accepted submit",
                                               .callback_parameter = "onSubmit",
                                               .description =
                                                   "Emitted only after enabled fields pass the "
                                                   "configured validation policy."}},
                .retained_state = {},
                .allows_children = true},
            DeclaredWidget{
                .name = "MenuBar",
                .parameters =
                    {DeclaredParameter{.name = "commands", .type = declared_type_reference("t78")},
                     DeclaredParameter{.name = "menuWidth", .type = declared_type_reference("t3")},
                     DeclaredParameter{.name = "rowHeight", .type = declared_type_reference("t3")}},
                .parameter_order = {"commands",
                                    "key",
                                    "menuWidth",
                                    "rowHeight",
                                    "layout",
                                    "variant",
                                    "style",
                                    "visualStyle",
                                    "effect",
                                    "material",
                                    "transition",
                                    "enter",
                                    "exit",
                                    "move",
                                    "motions",
                                    "animateChanges",
                                    "animateContentSize",
                                    "disclosure",
                                    "contentKey",
                                    "contentTransition",
                                    "contentTransitionMode",
                                    "stagger",
                                    "semantics",
                                    "textStyle",
                                    "textVisualStyle",
                                    "animation",
                                    "behaviors"},
                .bindings = {},
                .events = {},
                .retained_state = {DeclaredRetainedState{
                    .name = "menu", .description = "Open top-level menu and active command row."}},
                .allows_children = true},
            DeclaredWidget{
                .name = "Modal",
                .parameters =
                    {DeclaredParameter{.name = "open", .type = declared_type_reference("t2")},
                     DeclaredParameter{.name = "dismissible",
                                       .type = declared_type_reference("t2")},
                     DeclaredParameter{.name = "onDismiss", .type = declared_type_reference("t36")},
                     DeclaredParameter{.name = "bind", .type = declared_type_reference("t7")}},
                .parameter_order = {"key",
                                    "open",
                                    "dismissible",
                                    "layout",
                                    "variant",
                                    "style",
                                    "visualStyle",
                                    "effect",
                                    "material",
                                    "transition",
                                    "enter",
                                    "exit",
                                    "move",
                                    "motions",
                                    "animateChanges",
                                    "animateContentSize",
                                    "disclosure",
                                    "contentKey",
                                    "contentTransition",
                                    "contentTransitionMode",
                                    "stagger",
                                    "semantics",
                                    "onDismiss",
                                    "bind",
                                    "textStyle",
                                    "textVisualStyle",
                                    "animation",
                                    "behaviors"},
                .bindings = {DeclaredWidgetBinding{.shorthand_parameter = "bind",
                                                   .value_parameter = "open",
                                                   .event_parameter = "onDismiss"}},
                .events = {DeclaredWidgetEvent{
                    .name = "dismissal request",
                    .callback_parameter = "onDismiss",
                    .description =
                        "Emitted when escape or the scrim requests closing a dismissible modal."}},
                .retained_state = {},
                .allows_children = true},
            DeclaredWidget{
                .name = "SplitPane",
                .parameters =
                    {DeclaredParameter{
                         .name = "key", .type = declared_type_reference("t4"), .required = true},
                     DeclaredParameter{.name = "axis", .type = declared_type_reference("t28")},
                     DeclaredParameter{
                         .name = "ratio", .type = declared_type_reference("t3"), .nullable = true},
                     DeclaredParameter{.name = "defaultRatio",
                                       .type = declared_type_reference("t3")},
                     DeclaredParameter{.name = "minRatio", .type = declared_type_reference("t3")},
                     DeclaredParameter{.name = "maxRatio", .type = declared_type_reference("t3")},
                     DeclaredParameter{.name = "dividerSize",
                                       .type = declared_type_reference("t3")},
                     DeclaredParameter{.name = "onChange", .type = declared_type_reference("t36")},
                     DeclaredParameter{.name = "bind", .type = declared_type_reference("t7")}},
                .parameter_order = {"key",
                                    "axis",
                                    "ratio",
                                    "defaultRatio",
                                    "minRatio",
                                    "maxRatio",
                                    "dividerSize",
                                    "layout",
                                    "variant",
                                    "style",
                                    "visualStyle",
                                    "effect",
                                    "material",
                                    "transition",
                                    "enter",
                                    "exit",
                                    "move",
                                    "motions",
                                    "animateChanges",
                                    "animateContentSize",
                                    "disclosure",
                                    "contentKey",
                                    "contentTransition",
                                    "contentTransitionMode",
                                    "stagger",
                                    "semantics",
                                    "onChange",
                                    "bind",
                                    "textStyle",
                                    "textVisualStyle",
                                    "animation",
                                    "behaviors"},
                .bindings = {DeclaredWidgetBinding{.shorthand_parameter = "bind",
                                                   .value_parameter = "ratio",
                                                   .event_parameter = "onChange"}},
                .events = {DeclaredWidgetEvent{
                    .name = "ratio change",
                    .callback_parameter = "onChange",
                    .description =
                        "Carries the clamped divider ratio requested by drag or keyboard input."}},
                .retained_state = {DeclaredRetainedState{
                    .name = "ratio",
                    .description = "Uncontrolled divider ratio initialized by `defaultRatio`."}},
                .allows_children = true},
            DeclaredWidget{
                .name = "ToastRegion",
                .parameters =
                    {DeclaredParameter{.name = "maxVisible", .type = declared_type_reference("t3")},
                     DeclaredParameter{.name = "width", .type = declared_type_reference("t3")},
                     DeclaredParameter{.name = "gap", .type = declared_type_reference("t3")},
                     DeclaredParameter{.name = "minHeight", .type = declared_type_reference("t3")},
                     DeclaredParameter{.name = "maxMessageLines",
                                       .type = declared_type_reference("t3")}},
                .parameter_order = {"key",
                                    "maxVisible",
                                    "width",
                                    "gap",
                                    "minHeight",
                                    "maxMessageLines",
                                    "layout",
                                    "variant",
                                    "style",
                                    "visualStyle",
                                    "effect",
                                    "material",
                                    "transition",
                                    "enter",
                                    "exit",
                                    "move",
                                    "motions",
                                    "animateChanges",
                                    "animateContentSize",
                                    "disclosure",
                                    "contentKey",
                                    "contentTransition",
                                    "contentTransitionMode",
                                    "stagger",
                                    "semantics",
                                    "textStyle",
                                    "textVisualStyle",
                                    "animation",
                                    "behaviors"},
                .bindings = {},
                .events = {},
                .retained_state = {}},
            DeclaredWidget{
                .name = "Toolbar",
                .parameters =
                    {DeclaredParameter{.name = "commands", .type = declared_type_reference("t78")},
                     DeclaredParameter{.name = "itemWidth", .type = declared_type_reference("t3")},
                     DeclaredParameter{.name = "overflowWidth",
                                       .type = declared_type_reference("t3")}},
                .parameter_order = {"commands",
                                    "key",
                                    "itemWidth",
                                    "overflowWidth",
                                    "layout",
                                    "variant",
                                    "style",
                                    "visualStyle",
                                    "effect",
                                    "material",
                                    "transition",
                                    "enter",
                                    "exit",
                                    "move",
                                    "motions",
                                    "animateChanges",
                                    "animateContentSize",
                                    "disclosure",
                                    "contentKey",
                                    "contentTransition",
                                    "contentTransitionMode",
                                    "stagger",
                                    "semantics",
                                    "textStyle",
                                    "textVisualStyle",
                                    "animation",
                                    "behaviors"},
                .bindings = {},
                .events = {},
                .retained_state = {DeclaredRetainedState{
                    .name = "overflow",
                    .description = "Open overflow menu and adaptive visible command count."}}},
        });
}

} // namespace strata::compiler
