#include "compiler/builtin_catalog_internal.hpp"

namespace strata::compiler {

void add_builtin_helpers(BuiltinCatalog& catalog) {
    catalog.helpers = {
        DeclaredHelper{.name = "abs",
                       .implementation = "scalar",
                       .parameters = {DeclaredParameter{.name = "value",
                                                        .type = declared_type_reference("t3"),
                                                        .required = true}},
                       .return_type = declared_type_reference("t3"),
                       .capabilities = {"NUMERIC"}},
        DeclaredHelper{.name = "action",
                       .implementation = "scalar",
                       .parameters = {DeclaredParameter{.name = "name",
                                                        .type = declared_type_reference("t0"),
                                                        .required = true}},
                       .return_type = declared_type_reference("t36"),
                       .vararg_type = declared_type_reference("t7"),
                       .capabilities = {"ACTION"},
                       .allow_named_varargs = true},
        DeclaredHelper{.name = "all",
                       .implementation = "all",
                       .parameters = {DeclaredParameter{.name = "source",
                                                        .type = declared_type_reference("t7"),
                                                        .required = true},
                                      DeclaredParameter{.name = "predicate",
                                                        .type = declared_type_reference("t7")}},
                       .return_type = declared_type_reference("t2"),
                       .capabilities = {"COLLECTION"}},
        DeclaredHelper{.name = "animation",
                       .implementation = "scalar",
                       .parameters = {DeclaredParameter{.name = "name",
                                                        .type = declared_type_reference("t0"),
                                                        .required = true}},
                       .return_type = declared_type_reference("t5"),
                       .capabilities = {"ANIMATION"}},
        DeclaredHelper{.name = "any",
                       .implementation = "any",
                       .parameters = {DeclaredParameter{.name = "source",
                                                        .type = declared_type_reference("t7"),
                                                        .required = true},
                                      DeclaredParameter{.name = "predicate",
                                                        .type = declared_type_reference("t7")}},
                       .return_type = declared_type_reference("t2"),
                       .capabilities = {"COLLECTION"}},
        DeclaredHelper{.name = "ceil",
                       .implementation = "scalar",
                       .parameters = {DeclaredParameter{.name = "value",
                                                        .type = declared_type_reference("t3"),
                                                        .required = true}},
                       .return_type = declared_type_reference("t3"),
                       .capabilities = {"NUMERIC"}},
        DeclaredHelper{.name = "chooseAction",
                       .implementation = "action_choose",
                       .parameters = {DeclaredParameter{.name = "condition",
                                                        .type = declared_type_reference("t2"),
                                                        .required = true},
                                      DeclaredParameter{.name = "whenTrue",
                                                        .type = declared_type_reference("t36"),
                                                        .required = true},
                                      DeclaredParameter{.name = "whenFalse",
                                                        .type = declared_type_reference("t36"),
                                                        .required = true}},
                       .return_type = declared_type_reference("t36"),
                       .capabilities = {"ACTION"}},
        DeclaredHelper{.name = "clamp",
                       .implementation = "scalar",
                       .parameters = {DeclaredParameter{.name = "value",
                                                        .type = declared_type_reference("t3"),
                                                        .required = true},
                                      DeclaredParameter{.name = "min",
                                                        .type = declared_type_reference("t3"),
                                                        .required = true},
                                      DeclaredParameter{.name = "max",
                                                        .type = declared_type_reference("t3"),
                                                        .required = true}},
                       .return_type = declared_type_reference("t3"),
                       .capabilities = {"NUMERIC"}},
        DeclaredHelper{.name = "contains",
                       .implementation = "scalar",
                       .parameters = {DeclaredParameter{.name = "value",
                                                        .type = declared_type_reference("t7"),
                                                        .required = true},
                                      DeclaredParameter{.name = "needle",
                                                        .type = declared_type_reference("t7"),
                                                        .required = true}},
                       .return_type = declared_type_reference("t2"),
                       .capabilities = {"COLLECTION"}},
        DeclaredHelper{.name = "count",
                       .implementation = "count",
                       .parameters = {DeclaredParameter{.name = "source",
                                                        .type = declared_type_reference("t7"),
                                                        .required = true},
                                      DeclaredParameter{.name = "predicate",
                                                        .type = declared_type_reference("t7")}},
                       .return_type = declared_type_reference("t3"),
                       .capabilities = {"COLLECTION"}},
        DeclaredHelper{.name = "distinctBy",
                       .implementation = "distinct_by",
                       .parameters = {DeclaredParameter{.name = "source",
                                                        .type = declared_type_reference("t7"),
                                                        .required = true},
                                      DeclaredParameter{.name = "selector",
                                                        .type = declared_type_reference("t7"),
                                                        .required = true}},
                       .return_type = declared_type_reference("t107"),
                       .capabilities = {"COLLECTION"}},
        DeclaredHelper{.name = "effect",
                       .implementation = "scalar",
                       .parameters = {DeclaredParameter{.name = "name",
                                                        .type = declared_type_reference("t0"),
                                                        .required = true}},
                       .return_type = declared_type_reference("t41"),
                       .vararg_type = declared_type_reference("t7"),
                       .capabilities = {"EFFECT"},
                       .allow_named_varargs = true},
        DeclaredHelper{.name = "endsWith",
                       .implementation = "scalar",
                       .parameters = {DeclaredParameter{.name = "value",
                                                        .type = declared_type_reference("t0"),
                                                        .required = true},
                                      DeclaredParameter{.name = "suffix",
                                                        .type = declared_type_reference("t0"),
                                                        .required = true}},
                       .return_type = declared_type_reference("t2"),
                       .capabilities = {"TEXT"}},
        DeclaredHelper{.name = "filter",
                       .implementation = "filter",
                       .parameters = {DeclaredParameter{.name = "source",
                                                        .type = declared_type_reference("t7"),
                                                        .required = true},
                                      DeclaredParameter{.name = "predicate",
                                                        .type = declared_type_reference("t7"),
                                                        .required = true}},
                       .return_type = declared_type_reference("t107"),
                       .capabilities = {"COLLECTION"}},
        DeclaredHelper{.name = "flatten",
                       .implementation = "flatten",
                       .parameters = {DeclaredParameter{.name = "source",
                                                        .type = declared_type_reference("t7"),
                                                        .required = true}},
                       .return_type = declared_type_reference("t107"),
                       .capabilities = {"COLLECTION"}},
        DeclaredHelper{.name = "floor",
                       .implementation = "scalar",
                       .parameters = {DeclaredParameter{.name = "value",
                                                        .type = declared_type_reference("t3"),
                                                        .required = true}},
                       .return_type = declared_type_reference("t3"),
                       .capabilities = {"NUMERIC"}},
        DeclaredHelper{.name = "format",
                       .implementation = "scalar",
                       .parameters = {DeclaredParameter{.name = "pattern",
                                                        .type = declared_type_reference("t0"),
                                                        .required = true}},
                       .return_type = declared_type_reference("t0"),
                       .vararg_type = declared_type_reference("t7"),
                       .capabilities = {"FORMATTING"}},
        DeclaredHelper{.name = "formatNumber",
                       .implementation = "scalar",
                       .parameters = {DeclaredParameter{.name = "value",
                                                        .type = declared_type_reference("t3"),
                                                        .required = true},
                                      DeclaredParameter{.name = "precision",
                                                        .type = declared_type_reference("t3")}},
                       .return_type = declared_type_reference("t0"),
                       .capabilities = {"FORMATTING"}},
        DeclaredHelper{.name = "groupBy",
                       .implementation = "group_by",
                       .parameters = {DeclaredParameter{.name = "source",
                                                        .type = declared_type_reference("t7"),
                                                        .required = true},
                                      DeclaredParameter{.name = "selector",
                                                        .type = declared_type_reference("t7"),
                                                        .required = true}},
                       .return_type = declared_type_reference("t107"),
                       .capabilities = {"COLLECTION"}},
        DeclaredHelper{.name = "isEmpty",
                       .implementation = "scalar",
                       .parameters = {DeclaredParameter{.name = "value",
                                                        .type = declared_type_reference("t7"),
                                                        .required = true}},
                       .return_type = declared_type_reference("t2"),
                       .capabilities = {"COLLECTION"}},
        DeclaredHelper{.name = "join",
                       .implementation = "scalar",
                       .parameters = {DeclaredParameter{.name = "value",
                                                        .type = declared_type_reference("t108"),
                                                        .required = true},
                                      DeclaredParameter{.name = "separator",
                                                        .type = declared_type_reference("t0")}},
                       .return_type = declared_type_reference("t0"),
                       .capabilities = {"COLLECTION"}},
        DeclaredHelper{.name = "length",
                       .implementation = "scalar",
                       .parameters = {DeclaredParameter{.name = "value",
                                                        .type = declared_type_reference("t7"),
                                                        .required = true}},
                       .return_type = declared_type_reference("t3"),
                       .capabilities = {"COLLECTION"}},
        DeclaredHelper{.name = "lower",
                       .implementation = "scalar",
                       .parameters = {DeclaredParameter{.name = "value",
                                                        .type = declared_type_reference("t0"),
                                                        .required = true}},
                       .return_type = declared_type_reference("t0"),
                       .capabilities = {"TEXT"}},
        DeclaredHelper{.name = "map",
                       .implementation = "map",
                       .parameters = {DeclaredParameter{.name = "source",
                                                        .type = declared_type_reference("t7"),
                                                        .required = true},
                                      DeclaredParameter{.name = "transform",
                                                        .type = declared_type_reference("t7"),
                                                        .required = true}},
                       .return_type = declared_type_reference("t107"),
                       .capabilities = {"COLLECTION"}},
        DeclaredHelper{.name = "material",
                       .implementation = "scalar",
                       .parameters = {DeclaredParameter{
                           .name = "id", .type = declared_type_reference("t0"), .required = true}},
                       .return_type = declared_type_reference("t51"),
                       .vararg_type = declared_type_reference("t7"),
                       .capabilities = {"MATERIAL"},
                       .allow_named_varargs = true},
        DeclaredHelper{.name = "max",
                       .implementation = "scalar",
                       .parameters = {DeclaredParameter{.name = "first",
                                                        .type = declared_type_reference("t3"),
                                                        .required = true},
                                      DeclaredParameter{.name = "second",
                                                        .type = declared_type_reference("t3"),
                                                        .required = true}},
                       .return_type = declared_type_reference("t3"),
                       .vararg_type = declared_type_reference("t3"),
                       .capabilities = {"NUMERIC"}},
        DeclaredHelper{.name = "min",
                       .implementation = "scalar",
                       .parameters = {DeclaredParameter{.name = "first",
                                                        .type = declared_type_reference("t3"),
                                                        .required = true},
                                      DeclaredParameter{.name = "second",
                                                        .type = declared_type_reference("t3"),
                                                        .required = true}},
                       .return_type = declared_type_reference("t3"),
                       .vararg_type = declared_type_reference("t3"),
                       .capabilities = {"NUMERIC"}},
        DeclaredHelper{.name = "page",
                       .implementation = "page",
                       .parameters = {DeclaredParameter{.name = "source",
                                                        .type = declared_type_reference("t7"),
                                                        .required = true},
                                      DeclaredParameter{.name = "index",
                                                        .type = declared_type_reference("t3"),
                                                        .required = true},
                                      DeclaredParameter{.name = "size",
                                                        .type = declared_type_reference("t3"),
                                                        .required = true}},
                       .return_type = declared_type_reference("t107"),
                       .capabilities = {"COLLECTION"}},
        DeclaredHelper{.name = "parallel",
                       .implementation = "action_parallel",
                       .parameters = {DeclaredParameter{.name = "first",
                                                        .type = declared_type_reference("t36"),
                                                        .required = true}},
                       .return_type = declared_type_reference("t36"),
                       .vararg_type = declared_type_reference("t36"),
                       .capabilities = {"ACTION"}},
        DeclaredHelper{.name = "persisted",
                       .implementation = "persisted",
                       .parameters = {DeclaredParameter{.name = "key",
                                                        .type = declared_type_reference("t0"),
                                                        .required = true},
                                      DeclaredParameter{.name = "initial",
                                                        .type = declared_type_reference("t7"),
                                                        .required = true,
                                                        .nullable = true}},
                       .return_type = declared_type_reference("t7"),
                       .capabilities = {"PERSISTENCE"}},
        DeclaredHelper{.name = "rgb",
                       .implementation = "scalar",
                       .parameters = {DeclaredParameter{.name = "red",
                                                        .type = declared_type_reference("t3"),
                                                        .required = true},
                                      DeclaredParameter{.name = "green",
                                                        .type = declared_type_reference("t3"),
                                                        .required = true},
                                      DeclaredParameter{.name = "blue",
                                                        .type = declared_type_reference("t3"),
                                                        .required = true}},
                       .return_type = declared_type_reference("t8"),
                       .capabilities = {"COLOR"}},
        DeclaredHelper{.name = "rgba",
                       .implementation = "scalar",
                       .parameters = {DeclaredParameter{.name = "red",
                                                        .type = declared_type_reference("t3"),
                                                        .required = true},
                                      DeclaredParameter{.name = "green",
                                                        .type = declared_type_reference("t3"),
                                                        .required = true},
                                      DeclaredParameter{.name = "blue",
                                                        .type = declared_type_reference("t3"),
                                                        .required = true},
                                      DeclaredParameter{.name = "alpha",
                                                        .type = declared_type_reference("t3"),
                                                        .required = true}},
                       .return_type = declared_type_reference("t8"),
                       .capabilities = {"COLOR"}},
        DeclaredHelper{.name = "round",
                       .implementation = "scalar",
                       .parameters = {DeclaredParameter{.name = "value",
                                                        .type = declared_type_reference("t3"),
                                                        .required = true},
                                      DeclaredParameter{.name = "precision",
                                                        .type = declared_type_reference("t3")}},
                       .return_type = declared_type_reference("t3"),
                       .capabilities = {"NUMERIC"}},
        DeclaredHelper{.name = "sequence",
                       .implementation = "action_sequence",
                       .parameters = {DeclaredParameter{.name = "first",
                                                        .type = declared_type_reference("t36"),
                                                        .required = true}},
                       .return_type = declared_type_reference("t36"),
                       .vararg_type = declared_type_reference("t36"),
                       .capabilities = {"ACTION"}},
        DeclaredHelper{.name = "size",
                       .implementation = "scalar",
                       .parameters = {DeclaredParameter{.name = "value",
                                                        .type = declared_type_reference("t7"),
                                                        .required = true}},
                       .return_type = declared_type_reference("t3"),
                       .capabilities = {"COLLECTION"}},
        DeclaredHelper{.name = "sortBy",
                       .implementation = "sort_by",
                       .parameters = {DeclaredParameter{.name = "source",
                                                        .type = declared_type_reference("t7"),
                                                        .required = true},
                                      DeclaredParameter{.name = "selector",
                                                        .type = declared_type_reference("t7"),
                                                        .required = true},
                                      DeclaredParameter{.name = "descending",
                                                        .type = declared_type_reference("t2")}},
                       .return_type = declared_type_reference("t107"),
                       .capabilities = {"COLLECTION"}},
        DeclaredHelper{.name = "startsWith",
                       .implementation = "scalar",
                       .parameters = {DeclaredParameter{.name = "value",
                                                        .type = declared_type_reference("t0"),
                                                        .required = true},
                                      DeclaredParameter{.name = "prefix",
                                                        .type = declared_type_reference("t0"),
                                                        .required = true}},
                       .return_type = declared_type_reference("t2"),
                       .capabilities = {"TEXT"}},
        DeclaredHelper{.name = "style",
                       .implementation = "scalar",
                       .parameters = {},
                       .return_type = declared_type_reference("t57"),
                       .vararg_type = declared_type_reference("t7"),
                       .capabilities = {"STYLE"},
                       .allow_named_varargs = true},
        DeclaredHelper{
            .name = "whenStyle",
            .implementation = "when_style",
            .parameters = {
                DeclaredParameter{
                    .name = "condition",
                    .type = declared_type_reference("t2"),
                    .required = true,
                },
                DeclaredParameter{
                    .name = "active",
                    .type = declared_type_reference("t57"),
                    .required = true,
                },
            },
            .return_type = declared_type_reference("t57"),
            .capabilities = {"STYLE"},
        },
        DeclaredHelper{.name = "takeWhile",
                       .implementation = "take_while",
                       .parameters = {DeclaredParameter{.name = "source",
                                                        .type = declared_type_reference("t7"),
                                                        .required = true},
                                      DeclaredParameter{.name = "predicate",
                                                        .type = declared_type_reference("t7"),
                                                        .required = true}},
                       .return_type = declared_type_reference("t107"),
                       .capabilities = {"COLLECTION"}},
        DeclaredHelper{.name = "title",
                       .implementation = "scalar",
                       .parameters = {DeclaredParameter{.name = "value",
                                                        .type = declared_type_reference("t0"),
                                                        .required = true}},
                       .return_type = declared_type_reference("t0"),
                       .capabilities = {"TEXT"}},
        DeclaredHelper{.name = "trim",
                       .implementation = "scalar",
                       .parameters = {DeclaredParameter{.name = "value",
                                                        .type = declared_type_reference("t0"),
                                                        .required = true}},
                       .return_type = declared_type_reference("t0"),
                       .capabilities = {"TEXT"}},
        DeclaredHelper{.name = "upper",
                       .implementation = "scalar",
                       .parameters = {DeclaredParameter{.name = "value",
                                                        .type = declared_type_reference("t0"),
                                                        .required = true}},
                       .return_type = declared_type_reference("t0"),
                       .capabilities = {"TEXT"}},
        DeclaredHelper{.name = "window",
                       .implementation = "window",
                       .parameters = {DeclaredParameter{.name = "source",
                                                        .type = declared_type_reference("t7"),
                                                        .required = true},
                                      DeclaredParameter{.name = "offset",
                                                        .type = declared_type_reference("t3"),
                                                        .required = true},
                                      DeclaredParameter{.name = "limit",
                                                        .type = declared_type_reference("t3"),
                                                        .required = true}},
                       .return_type = declared_type_reference("t107"),
                       .capabilities = {"COLLECTION"}},
    };
}

} // namespace strata::compiler
