#include "compiler/builtin_catalog_internal.hpp"

namespace strata::compiler {

void add_builtin_control_widgets(BuiltinCatalog& catalog) {
    catalog.widgets.insert(
        catalog.widgets.end(),
        {
            DeclaredWidget{
                .name = "Checkbox",
                .parameters =
                    {DeclaredParameter{.name = "label", .type = declared_type_reference("t0")},
                     DeclaredParameter{.name = "checked",
                                       .type = declared_type_reference("t2"),
                                       .nullable = true},
                     DeclaredParameter{.name = "defaultChecked",
                                       .type = declared_type_reference("t2")},
                     DeclaredParameter{.name = "enabled", .type = declared_type_reference("t2")},
                     DeclaredParameter{.name = "onChange", .type = declared_type_reference("t36")},
                     DeclaredParameter{.name = "bind", .type = declared_type_reference("t7")}},
                .parameter_order = {"label",
                                    "key",
                                    "checked",
                                    "defaultChecked",
                                    "enabled",
                                    "layout",
                                    "variant",
                                    "style",
                                    "visualStyle",
                                    "effect",
                                    "material",
                                    "transition",
                                    "enter",
                                    "exit",
                                    "move",
                                    "motions",
                                    "animateChanges",
                                    "animateContentSize",
                                    "disclosure",
                                    "contentKey",
                                    "contentTransition",
                                    "contentTransitionMode",
                                    "stagger",
                                    "semantics",
                                    "textStyle",
                                    "textVisualStyle",
                                    "animation",
                                    "onChange",
                                    "bind",
                                    "behaviors"},
                .bindings = {DeclaredWidgetBinding{.shorthand_parameter = "bind",
                                                   .value_parameter = "checked",
                                                   .event_parameter = "onChange"}},
                .events = {DeclaredWidgetEvent{.name = "checked change",
                                               .callback_parameter = "onChange",
                                               .description =
                                                   "Carries the newly requested checked value."}},
                .retained_state = {DeclaredRetainedState{
                    .name = "checked",
                    .description = "Uncontrolled checked value initialized by `defaultChecked`."}}},
            DeclaredWidget{
                .name = "ComboBox",
                .parameters =
                    {DeclaredParameter{
                         .name = "key", .type = declared_type_reference("t4"), .required = true},
                     DeclaredParameter{.name = "options",
                                       .type = declared_type_reference("t60"),
                                       .required = true},
                     DeclaredParameter{.name = "query", .type = declared_type_reference("t0")},
                     DeclaredParameter{.name = "selectedId",
                                       .type = declared_type_reference("t0"),
                                       .nullable = true},
                     DeclaredParameter{.name = "enabled", .type = declared_type_reference("t2")},
                     DeclaredParameter{.name = "maxVisibleRows",
                                       .type = declared_type_reference("t3")},
                     DeclaredParameter{.name = "triggerTemplate",
                                       .type = declared_type_reference("t163")},
                     DeclaredParameter{.name = "popupTemplate",
                                       .type = declared_type_reference("t164")},
                     DeclaredParameter{.name = "itemTemplate",
                                       .type = declared_type_reference("t165")},
                     DeclaredParameter{.name = "onQuery", .type = declared_type_reference("t36")},
                     DeclaredParameter{.name = "onChange", .type = declared_type_reference("t36")},
                     DeclaredParameter{.name = "bindQuery", .type = declared_type_reference("t7")},
                     DeclaredParameter{.name = "bindSelected",
                                       .type = declared_type_reference("t7")}},
                .parameter_order = {"key",
                                    "options",
                                    "query",
                                    "selectedId",
                                    "enabled",
                                    "maxVisibleRows",
                                    "triggerTemplate",
                                    "popupTemplate",
                                    "itemTemplate",
                                    "onQuery",
                                    "onChange",
                                    "bindQuery",
                                    "bindSelected",
                                    "layout",
                                    "variant",
                                    "style",
                                    "visualStyle",
                                    "effect",
                                    "material",
                                    "transition",
                                    "enter",
                                    "exit",
                                    "move",
                                    "motions",
                                    "animateChanges",
                                    "animateContentSize",
                                    "disclosure",
                                    "contentKey",
                                    "contentTransition",
                                    "contentTransitionMode",
                                    "stagger",
                                    "semantics",
                                    "textStyle",
                                    "textVisualStyle",
                                    "animation",
                                    "behaviors"},
                .bindings = {DeclaredWidgetBinding{.shorthand_parameter = "bindQuery",
                                                   .value_parameter = "query",
                                                   .event_parameter = "onQuery"},
                             DeclaredWidgetBinding{.shorthand_parameter = "bindSelected",
                                                   .value_parameter = "selectedId",
                                                   .event_parameter = "onChange"}},
                .events = {DeclaredWidgetEvent{.name = "query change",
                                               .callback_parameter = "onQuery",
                                               .description = "Carries the edited search query."},
                           DeclaredWidgetEvent{
                               .name = "selection change",
                               .callback_parameter = "onChange",
                               .description = "Carries the id of the chosen filtered option."}},
                .retained_state =
                    {DeclaredRetainedState{.name = "query editor",
                                           .description =
                                               "Caret, selection, composition, undo history, and "
                                               "viewport for the keyed query editor."},
                     DeclaredRetainedState{.name = "selection popup",
                                           .description = "Selected option, expanded state, active "
                                                          "option, and visible option window."}}},
            DeclaredWidget{
                .name = "IconButton",
                .parameters =
                    {DeclaredParameter{
                         .name = "icon", .type = declared_type_reference("t66"), .required = true},
                     DeclaredParameter{.name = "label", .type = declared_type_reference("t0")},
                     DeclaredParameter{.name = "source", .type = declared_type_reference("t67")},
                     DeclaredParameter{.name = "enabled", .type = declared_type_reference("t2")},
                     DeclaredParameter{.name = "onClick", .type = declared_type_reference("t36")},
                     DeclaredParameter{.name = "command",
                                       .type = declared_type_reference("t0"),
                                       .nullable = true}},
                .parameter_order = {"icon",
                                    "key",
                                    "label",
                                    "source",
                                    "enabled",
                                    "layout",
                                    "variant",
                                    "style",
                                    "visualStyle",
                                    "effect",
                                    "material",
                                    "transition",
                                    "enter",
                                    "exit",
                                    "move",
                                    "motions",
                                    "animateChanges",
                                    "animateContentSize",
                                    "disclosure",
                                    "contentKey",
                                    "contentTransition",
                                    "contentTransitionMode",
                                    "stagger",
                                    "semantics",
                                    "textStyle",
                                    "textVisualStyle",
                                    "animation",
                                    "onClick",
                                    "command",
                                    "behaviors"},
                .bindings = {},
                .events = {DeclaredWidgetEvent{
                    .name = "activation",
                    .callback_parameter = "onClick",
                    .description = "Emitted after pointer or keyboard activation."}},
                .retained_state = {}},
            DeclaredWidget{
                .name = "NumberField",
                .parameters =
                    {DeclaredParameter{
                         .name = "key", .type = declared_type_reference("t4"), .required = true},
                     DeclaredParameter{
                         .name = "value", .type = declared_type_reference("t3"), .nullable = true},
                     DeclaredParameter{.name = "defaultValue",
                                       .type = declared_type_reference("t3")},
                     DeclaredParameter{
                         .name = "min", .type = declared_type_reference("t3"), .nullable = true},
                     DeclaredParameter{
                         .name = "max", .type = declared_type_reference("t3"), .nullable = true},
                     DeclaredParameter{.name = "step", .type = declared_type_reference("t3")},
                     DeclaredParameter{.name = "enabled", .type = declared_type_reference("t2")},
                     DeclaredParameter{.name = "onChange", .type = declared_type_reference("t36")},
                     DeclaredParameter{.name = "bind", .type = declared_type_reference("t7")}},
                .parameter_order =
                    {"key",
                     "value",
                     "defaultValue",
                     "min",
                     "max",
                     "step",
                     "enabled",
                     "layout",
                     "variant",
                     "style",
                     "visualStyle",
                     "effect",
                     "material",
                     "transition",
                     "enter",
                     "exit",
                     "move",
                     "motions",
                     "animateChanges",
                     "animateContentSize",
                     "disclosure",
                     "contentKey",
                     "contentTransition",
                     "contentTransitionMode",
                     "stagger",
                     "semantics",
                     "textStyle",
                     "textVisualStyle",
                     "onChange",
                     "bind",
                     "animation",
                     "behaviors"},
                .bindings = {DeclaredWidgetBinding{.shorthand_parameter = "bind",
                                                   .value_parameter = "value",
                                                   .event_parameter = "onChange"}},
                .events = {DeclaredWidgetEvent{
                    .name = "value change",
                    .callback_parameter = "onChange",
                    .description =
                        "Carries the constrained numeric value after commit or stepping."}},
                .retained_state =
                    {DeclaredRetainedState{
                         .name = "value",
                         .description =
                             "Uncontrolled committed numeric value initialized by `defaultValue`."},
                     DeclaredRetainedState{
                         .name = "editing",
                         .description = "Text, caret, selection, undo history, and viewport for "
                                        "the keyed numeric editor."}}},
            DeclaredWidget{
                .name = "Progress",
                .parameters =
                    {DeclaredParameter{.name = "value", .type = declared_type_reference("t3")},
                     DeclaredParameter{.name = "min", .type = declared_type_reference("t3")},
                     DeclaredParameter{.name = "max", .type = declared_type_reference("t3")},
                     DeclaredParameter{.name = "indeterminate",
                                       .type = declared_type_reference("t2")}},
                .parameter_order =
                    {"key",
                     "value",
                     "min",
                     "max",
                     "indeterminate",
                     "layout",
                     "variant",
                     "style",
                     "visualStyle",
                     "effect",
                     "material",
                     "transition",
                     "enter",
                     "exit",
                     "move",
                     "motions",
                     "animateChanges",
                     "animateContentSize",
                     "disclosure",
                     "contentKey",
                     "contentTransition",
                     "contentTransitionMode",
                     "stagger",
                     "semantics",
                     "animation",
                     "textStyle",
                     "textVisualStyle",
                     "behaviors"},
                .bindings = {},
                .events = {},
                .retained_state = {}},
            DeclaredWidget{
                .name = "RadioGroup",
                .parameters =
                    {DeclaredParameter{
                         .name = "key", .type = declared_type_reference("t4"), .required = true},
                     DeclaredParameter{.name = "options",
                                       .type = declared_type_reference("t60"),
                                       .required = true},
                     DeclaredParameter{.name = "selectedId",
                                       .type = declared_type_reference("t0"),
                                       .nullable = true},
                     DeclaredParameter{.name = "defaultSelectedId",
                                       .type = declared_type_reference("t0"),
                                       .nullable = true},
                     DeclaredParameter{.name = "enabled", .type = declared_type_reference("t2")},
                     DeclaredParameter{.name = "onChange", .type = declared_type_reference("t36")},
                     DeclaredParameter{.name = "bind", .type = declared_type_reference("t7")}},
                .parameter_order = {"key",
                                    "options",
                                    "selectedId",
                                    "defaultSelectedId",
                                    "enabled",
                                    "layout",
                                    "variant",
                                    "style",
                                    "visualStyle",
                                    "effect",
                                    "material",
                                    "transition",
                                    "enter",
                                    "exit",
                                    "move",
                                    "motions",
                                    "animateChanges",
                                    "animateContentSize",
                                    "disclosure",
                                    "contentKey",
                                    "contentTransition",
                                    "contentTransitionMode",
                                    "stagger",
                                    "semantics",
                                    "textStyle",
                                    "textVisualStyle",
                                    "onChange",
                                    "bind",
                                    "animation",
                                    "behaviors"},
                .bindings = {DeclaredWidgetBinding{.shorthand_parameter = "bind",
                                                   .value_parameter = "selectedId",
                                                   .event_parameter = "onChange"}},
                .events = {DeclaredWidgetEvent{
                    .name = "selection change",
                    .callback_parameter = "onChange",
                    .description = "Carries the id of the newly selected radio option."}},
                .retained_state = {DeclaredRetainedState{
                    .name = "selectedId",
                    .description =
                        "Uncontrolled selected option initialized by `defaultSelectedId`."}}},
            DeclaredWidget{
                .name = "Select",
                .parameters =
                    {DeclaredParameter{.name = "options",
                                       .type = declared_type_reference("t60"),
                                       .required = true},
                     DeclaredParameter{.name = "selectedId",
                                       .type = declared_type_reference("t0"),
                                       .nullable = true},
                     DeclaredParameter{.name = "defaultSelectedId",
                                       .type = declared_type_reference("t0"),
                                       .nullable = true},
                     DeclaredParameter{.name = "expanded",
                                       .type = declared_type_reference("t2"),
                                       .nullable = true},
                     DeclaredParameter{.name = "defaultExpanded",
                                       .type = declared_type_reference("t2")},
                     DeclaredParameter{.name = "maxVisibleRows",
                                       .type = declared_type_reference("t3")},
                     DeclaredParameter{.name = "collapsedIcon",
                                       .type = declared_type_reference("t66")},
                     DeclaredParameter{.name = "expandedIcon",
                                       .type = declared_type_reference("t66")},
                     DeclaredParameter{.name = "triggerTemplate",
                                       .type = declared_type_reference("t163")},
                     DeclaredParameter{.name = "popupTemplate",
                                       .type = declared_type_reference("t164")},
                     DeclaredParameter{.name = "itemTemplate",
                                       .type = declared_type_reference("t165")},
                     DeclaredParameter{.name = "enabled", .type = declared_type_reference("t2")},
                     DeclaredParameter{.name = "onChange", .type = declared_type_reference("t36")},
                     DeclaredParameter{.name = "bind", .type = declared_type_reference("t7")}},
                .parameter_order = {"options",
                                    "key",
                                    "selectedId",
                                    "defaultSelectedId",
                                    "expanded",
                                    "defaultExpanded",
                                    "maxVisibleRows",
                                    "collapsedIcon",
                                    "expandedIcon",
                                    "triggerTemplate",
                                    "popupTemplate",
                                    "itemTemplate",
                                    "enabled",
                                    "layout",
                                    "variant",
                                    "style",
                                    "visualStyle",
                                    "effect",
                                    "material",
                                    "transition",
                                    "enter",
                                    "exit",
                                    "move",
                                    "motions",
                                    "animateChanges",
                                    "animateContentSize",
                                    "disclosure",
                                    "contentKey",
                                    "contentTransition",
                                    "contentTransitionMode",
                                    "stagger",
                                    "semantics",
                                    "textStyle",
                                    "textVisualStyle",
                                    "onChange",
                                    "bind",
                                    "animation",
                                    "behaviors"},
                .bindings = {DeclaredWidgetBinding{.shorthand_parameter = "bind",
                                                   .value_parameter = "selectedId",
                                                   .event_parameter = "onChange"}},
                .events = {DeclaredWidgetEvent{.name = "selection change",
                                               .callback_parameter = "onChange",
                                               .description =
                                                   "Carries the id of the chosen option."}},
                .retained_state =
                    {DeclaredRetainedState{
                         .name = "selectedId",
                         .description =
                             "Uncontrolled selected option initialized by `defaultSelectedId`."},
                     DeclaredRetainedState{.name = "popup",
                                           .description = "Uncontrolled expanded state, active "
                                                          "option, and visible option window."}}},
            DeclaredWidget{
                .name = "Slider",
                .parameters =
                    {DeclaredParameter{.name = "value",
                                       .type = declared_type_reference("t3"),
                                       .nullable = true},
                     DeclaredParameter{.name = "defaultValue",
                                       .type = declared_type_reference("t3")},
                     DeclaredParameter{.name = "min", .type = declared_type_reference("t3")},
                     DeclaredParameter{.name = "max", .type = declared_type_reference("t3")},
                     DeclaredParameter{
                         .name = "step", .type = declared_type_reference("t3"), .nullable = true},
                     DeclaredParameter{.name = "axis", .type = declared_type_reference("t28")},
                     DeclaredParameter{.name = "enabled", .type = declared_type_reference("t2")},
                     DeclaredParameter{.name = "onChange", .type = declared_type_reference("t36")},
                     DeclaredParameter{.name = "bind", .type = declared_type_reference("t7")}},
                .parameter_order =
                    {"key",
                     "value",
                     "defaultValue",
                     "min",
                     "max",
                     "step",
                     "axis",
                     "enabled",
                     "layout",
                     "variant",
                     "style",
                     "visualStyle",
                     "effect",
                     "material",
                     "transition",
                     "enter",
                     "exit",
                     "move",
                     "motions",
                     "animateChanges",
                     "animateContentSize",
                     "disclosure",
                     "contentKey",
                     "contentTransition",
                     "contentTransitionMode",
                     "stagger",
                     "semantics",
                     "textStyle",
                     "textVisualStyle",
                     "animation",
                     "onChange",
                     "bind",
                     "behaviors"},
                .bindings = {DeclaredWidgetBinding{.shorthand_parameter = "bind",
                                                   .value_parameter = "value",
                                                   .event_parameter = "onChange"}},
                .events = {DeclaredWidgetEvent{
                    .name = "value change",
                    .callback_parameter = "onChange",
                    .description =
                        "Carries the clamped and quantized value requested by the user."}},
                .retained_state = {DeclaredRetainedState{
                    .name = "value",
                    .description = "Uncontrolled numeric value initialized by `defaultValue`."}}},
            DeclaredWidget{
                .name = "Tabs",
                .parameters =
                    {DeclaredParameter{
                         .name = "tabs", .type = declared_type_reference("t64"), .required = true},
                     DeclaredParameter{.name = "selectedId",
                                       .type = declared_type_reference("t0"),
                                       .nullable = true},
                     DeclaredParameter{.name = "defaultSelectedId",
                                       .type = declared_type_reference("t0"),
                                       .nullable = true},
                     DeclaredParameter{.name = "onChange", .type = declared_type_reference("t36")},
                     DeclaredParameter{.name = "bind", .type = declared_type_reference("t7")}},
                .parameter_order = {"tabs",
                                    "key",
                                    "selectedId",
                                    "defaultSelectedId",
                                    "layout",
                                    "variant",
                                    "style",
                                    "visualStyle",
                                    "effect",
                                    "material",
                                    "transition",
                                    "enter",
                                    "exit",
                                    "move",
                                    "motions",
                                    "animateChanges",
                                    "animateContentSize",
                                    "disclosure",
                                    "contentKey",
                                    "contentTransition",
                                    "contentTransitionMode",
                                    "stagger",
                                    "semantics",
                                    "textStyle",
                                    "textVisualStyle",
                                    "onChange",
                                    "bind",
                                    "animation",
                                    "behaviors"},
                .bindings = {DeclaredWidgetBinding{.shorthand_parameter = "bind",
                                                   .value_parameter = "selectedId",
                                                   .event_parameter = "onChange"}},
                .events = {DeclaredWidgetEvent{.name = "selection change",
                                               .callback_parameter = "onChange",
                                               .description =
                                                   "Carries the id of the newly selected tab."}},
                .retained_state = {DeclaredRetainedState{
                    .name = "selectedId",
                    .description =
                        "Uncontrolled selected tab initialized by `defaultSelectedId`."}}},
            DeclaredWidget{
                .name = "TextArea",
                .parameters =
                    {DeclaredParameter{
                         .name = "text", .type = declared_type_reference("t0"), .required = true},
                     DeclaredParameter{.name = "hint", .type = declared_type_reference("t0")},
                     DeclaredParameter{.name = "enabled", .type = declared_type_reference("t2")},
                     DeclaredParameter{.name = "readOnly", .type = declared_type_reference("t2")},
                     DeclaredParameter{.name = "maxLength",
                                       .type = declared_type_reference("t3"),
                                       .nullable = true},
                     DeclaredParameter{.name = "filter", .type = declared_type_reference("t134")},
                     DeclaredParameter{.name = "commitFormat",
                                       .type = declared_type_reference("t135")},
                     DeclaredParameter{.name = "wrapWidth",
                                       .type = declared_type_reference("t3"),
                                       .nullable = true},
                     DeclaredParameter{.name = "wrapMode", .type = declared_type_reference("t69")},
                     DeclaredParameter{.name = "overflow", .type = declared_type_reference("t55")},
                     DeclaredParameter{.name = "maxLines",
                                       .type = declared_type_reference("t3"),
                                       .nullable = true},
                     DeclaredParameter{.name = "alignment", .type = declared_type_reference("t65")},
                     DeclaredParameter{.name = "selectable", .type = declared_type_reference("t2")},
                     DeclaredParameter{.name = "selectionContainer",
                                       .type = declared_type_reference("t0"),
                                       .nullable = true},
                     DeclaredParameter{.name = "onChange", .type = declared_type_reference("t36")},
                     DeclaredParameter{.name = "bind", .type = declared_type_reference("t7")}},
                .parameter_order = {"text",
                                    "key",
                                    "hint",
                                    "enabled",
                                    "readOnly",
                                    "maxLength",
                                    "filter",
                                    "commitFormat",
                                    "layout",
                                    "variant",
                                    "style",
                                    "visualStyle",
                                    "effect",
                                    "material",
                                    "transition",
                                    "enter",
                                    "exit",
                                    "move",
                                    "motions",
                                    "animateChanges",
                                    "animateContentSize",
                                    "disclosure",
                                    "contentKey",
                                    "contentTransition",
                                    "contentTransitionMode",
                                    "stagger",
                                    "semantics",
                                    "textStyle",
                                    "textVisualStyle",
                                    "wrapWidth",
                                    "wrapMode",
                                    "overflow",
                                    "maxLines",
                                    "alignment",
                                    "selectable",
                                    "selectionContainer",
                                    "onChange",
                                    "bind",
                                    "animation",
                                    "behaviors"},
                .bindings = {DeclaredWidgetBinding{.shorthand_parameter = "bind",
                                                   .value_parameter = "text",
                                                   .event_parameter = "onChange"}},
                .events = {DeclaredWidgetEvent{
                    .name = "text change",
                    .callback_parameter = "onChange",
                    .description =
                        "Carries the accepted text after filtering and length constraints."}},
                .retained_state = {DeclaredRetainedState{
                    .name = "editing",
                    .description = "Text, caret, selection, composition, undo history, and "
                                   "viewport for the keyed editor."}}},
            DeclaredWidget{
                .name = "TextBox",
                .parameters =
                    {DeclaredParameter{
                         .name = "text", .type = declared_type_reference("t0"), .required = true},
                     DeclaredParameter{.name = "hint", .type = declared_type_reference("t0")},
                     DeclaredParameter{.name = "enabled", .type = declared_type_reference("t2")},
                     DeclaredParameter{.name = "readOnly", .type = declared_type_reference("t2")},
                     DeclaredParameter{.name = "password", .type = declared_type_reference("t2")},
                     DeclaredParameter{.name = "maxLength",
                                       .type = declared_type_reference("t3"),
                                       .nullable = true},
                     DeclaredParameter{.name = "filter", .type = declared_type_reference("t134")},
                     DeclaredParameter{.name = "commitFormat",
                                       .type = declared_type_reference("t135")},
                     DeclaredParameter{.name = "wrapWidth",
                                       .type = declared_type_reference("t3"),
                                       .nullable = true},
                     DeclaredParameter{.name = "wrapMode", .type = declared_type_reference("t69")},
                     DeclaredParameter{.name = "overflow", .type = declared_type_reference("t55")},
                     DeclaredParameter{.name = "maxLines",
                                       .type = declared_type_reference("t3"),
                                       .nullable = true},
                     DeclaredParameter{.name = "alignment", .type = declared_type_reference("t65")},
                     DeclaredParameter{.name = "selectable", .type = declared_type_reference("t2")},
                     DeclaredParameter{.name = "selectionContainer",
                                       .type = declared_type_reference("t0"),
                                       .nullable = true},
                     DeclaredParameter{.name = "onChange", .type = declared_type_reference("t36")},
                     DeclaredParameter{.name = "bind", .type = declared_type_reference("t7")}},
                .parameter_order = {"text",
                                    "key",
                                    "hint",
                                    "enabled",
                                    "readOnly",
                                    "password",
                                    "maxLength",
                                    "filter",
                                    "commitFormat",
                                    "layout",
                                    "variant",
                                    "style",
                                    "visualStyle",
                                    "effect",
                                    "material",
                                    "transition",
                                    "enter",
                                    "exit",
                                    "move",
                                    "motions",
                                    "animateChanges",
                                    "animateContentSize",
                                    "disclosure",
                                    "contentKey",
                                    "contentTransition",
                                    "contentTransitionMode",
                                    "stagger",
                                    "semantics",
                                    "textStyle",
                                    "textVisualStyle",
                                    "wrapWidth",
                                    "wrapMode",
                                    "overflow",
                                    "maxLines",
                                    "alignment",
                                    "selectable",
                                    "selectionContainer",
                                    "onChange",
                                    "bind",
                                    "animation",
                                    "behaviors"},
                .bindings = {DeclaredWidgetBinding{.shorthand_parameter = "bind",
                                                   .value_parameter = "text",
                                                   .event_parameter = "onChange"}},
                .events = {DeclaredWidgetEvent{
                    .name = "text change",
                    .callback_parameter = "onChange",
                    .description =
                        "Carries the accepted text after filtering and length constraints."}},
                .retained_state = {DeclaredRetainedState{
                    .name = "editing",
                    .description = "Text, caret, selection, composition, undo history, and "
                                   "viewport for the keyed editor."}}},
            DeclaredWidget{
                .name = "Toggle",
                .parameters =
                    {DeclaredParameter{.name = "label", .type = declared_type_reference("t0")},
                     DeclaredParameter{.name = "checked",
                                       .type = declared_type_reference("t2"),
                                       .nullable = true},
                     DeclaredParameter{.name = "defaultChecked",
                                       .type = declared_type_reference("t2")},
                     DeclaredParameter{.name = "enabled", .type = declared_type_reference("t2")},
                     DeclaredParameter{.name = "onChange", .type = declared_type_reference("t36")},
                     DeclaredParameter{.name = "bind", .type = declared_type_reference("t7")}},
                .parameter_order =
                    {"label",
                     "key",
                     "checked",
                     "defaultChecked",
                     "enabled",
                     "layout",
                     "variant",
                     "style",
                     "visualStyle",
                     "effect",
                     "material",
                     "transition",
                     "enter",
                     "exit",
                     "move",
                     "motions",
                     "animateChanges",
                     "animateContentSize",
                     "disclosure",
                     "contentKey",
                     "contentTransition",
                     "contentTransitionMode",
                     "stagger",
                     "semantics",
                     "textStyle",
                     "textVisualStyle",
                     "animation",
                     "onChange",
                     "bind",
                     "behaviors"},
                .bindings = {DeclaredWidgetBinding{.shorthand_parameter = "bind",
                                                   .value_parameter = "checked",
                                                   .event_parameter = "onChange"}},
                .events = {DeclaredWidgetEvent{.name = "checked change",
                                               .callback_parameter = "onChange",
                                               .description =
                                                   "Carries the newly requested checked value."}},
                .retained_state = {DeclaredRetainedState{
                    .name = "checked",
                    .description = "Uncontrolled checked value initialized by `defaultChecked`."}}},
        });
}

} // namespace strata::compiler
