#include "diagnostic_catalog.hpp"

#include <filesystem>
#include <fstream>
#include <map>
#include <regex>
#include <set>
#include <sstream>
#include <stdexcept>
#include <string>
#include <string_view>
#include <system_error>

#include "core/utf8.hpp"

namespace strata::tools {
namespace {

[[nodiscard]] bool source_extension(const std::filesystem::path& path) {
    const std::string extension = path.extension().generic_string();
    return extension == ".c" || extension == ".h" || extension == ".cpp" ||
           extension == ".hpp" || extension == ".java" || extension == ".kt";
}

[[nodiscard]] std::string read_text(const std::filesystem::path& path) {
    std::ifstream input(path, std::ios::binary);
    if (!input) throw std::runtime_error("could not read diagnostic source");
    std::ostringstream output;
    output << input.rdbuf();
    std::string text = output.str();
    if (!core::valid_utf8(text)) throw std::runtime_error("diagnostic source is not valid UTF-8");
    return text;
}

} // namespace

std::string render_diagnostic_catalog(const std::filesystem::path& project_root) {
    const std::filesystem::path roots[]{
        project_root / "native/src",
        project_root / "native/desktop",
        project_root / "native/d3d11",
        project_root / "native/headless",
        project_root / "native/host",
        project_root / "native/tools",
    };
    const std::regex pattern(R"REGEX("(STRATA(?:\.[A-Z0-9_-]*[A-Z0-9])+)"\s*)REGEX");
    std::map<std::string, std::set<std::string>> locations;
    for (const std::filesystem::path& root : roots) {
        std::error_code error;
        if (!std::filesystem::is_directory(root, error) || error) continue;
        for (std::filesystem::recursive_directory_iterator iterator(root, error), end;
             iterator != end && !error;
             iterator.increment(error)) {
            if (!iterator->is_regular_file() || !source_extension(iterator->path())) continue;
            const std::string source = read_text(iterator->path());
            const std::string relative = std::filesystem::relative(
                iterator->path(), project_root, error
            ).generic_string();
            if (error) throw std::runtime_error("could not relativize diagnostic source path");
            for (std::sregex_iterator match(source.begin(), source.end(), pattern), finish;
                 match != finish;
                 ++match) {
                locations[(*match)[1].str()].emplace(relative);
            }
        }
        if (error) throw std::runtime_error("could not traverse diagnostic source tree");
    }
    if (locations.empty()) throw std::runtime_error("no production diagnostic codes were discovered");

    std::ostringstream output;
    output << "# Strata diagnostic catalog\n\n"
              "> Generated by the native authoring tool from production source declarations. Do not edit by hand.\n\n"
              "The source-owner column is deliberately exact: adding, removing, or moving a diagnostic updates this catalog.\n\n"
              "| Code | Source owners |\n"
              "|---|---|\n";
    for (const auto& [code, sources] : locations) {
        output << "| `" << code << "` | ";
        bool first = true;
        for (const std::string& source : sources) {
            if (!first) output << "<br>";
            output << '`' << source << '`';
            first = false;
        }
        output << " |\n";
    }
    return output.str();
}

} // namespace strata::tools
